### ISSUE TITLE
Shortcut_items uses manifest_url when it should use start_url

### ISSUE THREAD

**Issue by dmurph** [w3c/manifest#1003]
The algorithm to process shortcut items uses manifest url, and this origin can be different than the start_url origin. I think this is a mistake - the shortcuts should fall within scope of the web app, and on the same origin, at the very least.

**Comment by dominickng** [comment]
Note that shortcut items have an explicit [in-scope check](https://www.w3.org/TR/appmanifest/#dfn-process-a-shortcut) for URLs.

**Comment by LuHuangMSFT** [comment]
https://www.w3.org/TR/appmanifest/#processing-shortcut-items states:
> If url is not within scope of manifest URL, return failure.

I'm not sure what "scope of manifest URL" means when the manifest URL is not within the app's navigation scope, or even in the same origin. I think this needs to be clarified or edited.

Reddit's manifest is a current example of this issue. 
The manifest URL is: https://www.redditstatic.com/desktop2x/img/favicon/manifest.json?v=2
It has shortcuts written in a way that assume the shortcut URLs are relative to the app scope. In Chrome, they are resolved with the manifest URL's origin, then checked against navigation scope. This causes a "property 'url' ignored, should be within scope of the manifest" parsing error, causing the shortcuts to be ignored. 

```
{
      "name": "All",
      "short_name": "All",
      "url": "/r/all",
      "icons": [{ "src": "./shortcuts/icon_all_fill.png", "sizes": "192x192" }]
}
```

If this is the expected behavior, is it implicitly saying that shortcuts only work when the manifest URL is within navigation scope?

**Comment by marcoscaceres** [comment]
Yeah, this needs clarification... added it to the CR list todo.

**Comment by dmurph** [comment]
I worry that doing relative to scope might cause breakage here as previous relative urls are relative to the manifest url. This means that existing sites that have the manifest url at, say, `site.com/site_a/resources/manifest.json`, and then their scope is `site.com/site_a`, could have have relative urls like so: `start_url: "../../index.html"`, which resolves w/ the manifest base url as `site.com/site_a/index.html`.

If we changed the base_url to be the scope, then this would make it resolve to `site.com/index.html`.

This has come up a LOT as confusion for folks, and obviously for webapps. I think that we either:
1. Decide to possibly break sites by changing the base_url of everything to start_url or scope, or
2. Make it more obvious in the specification that relative urls are resolved in terms of the manifest_url, and to avoid confusion absolute urls should be used.

Obviously 1. would break things so I don't think we should do that.

I bet that #1018 could include the documentation.
