### ISSUE TITLE
A way to link to related applications

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#326]
It would be nice if there was a way for web apps to indicate that there is an equivalent native app - by providing a link to an application store or marketplace. 

Apple, for instance, provides "[app banners](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html)": 

```HTML
<meta name="apple-itunes-app" content="app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL">
``` 

And Microsoft has the following [meta tags](https://msdn.microsoft.com/en-us/library/ie/hh781489%28v=vs.85%29.aspx):

```HTML
<meta name="msApplication-ID"content="microsoft.build.App"/>
<meta name="msApplication-PackageFamilyName"content="microsoft.build_8wekyb3d8bbwe"/>
```
Such a feature could help with the "door slam" problem.

**Comment by kenchris** [comment]
On blink-dev there is currently a discussion/proposal for adding app banners based on web app manifest

**Comment by marcoscaceres** [comment]
oh? Link please!

**Comment by kenchris** [comment]
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/HSSqpbYd8W8

**Comment by benfrancis** [comment]
This sounds bad for the web as it risks further fragmenting the web into multiple walled gardens of content. Whether or not to include this in the spec probably comes down to what is the lesser of two evils:
a) Putting up with the current slam-door approach of mobile web sites which force users to download a non-web app based on a UA string by refusing to display, and the use of proprietary meta tags.
b) Adding something to the web manifest spec which is explicitly not to do with web apps and is intended to draw users away from the web.

I actually quite like Android's:
  <link rel="alternate" href="android-app://com.example.android/example/gizmos" />

except that the href attribute points to a non-web "hypertext reference" with a proprietary URL scheme.

If we wanted to add something similar to the manifest to link to alternative apps, ideally the alternative app would have a web URL and a Content Type:

  {
    "name": "Facebook",
    ...
    "alternate": [
      {
        "type": "application/vnd.android.package-archive",
        "href": "https://play.google.com/store/apps/details?id=com.facebook.katana"
       },
       {
         "type": "application/x-chrome-extension",
         "href": "https://chrome.google.com/webstore/detail/facebook/boeajhmfdjldchidhphikilcgdacljfm"
       },
       {
         "type": "application/octet-stream",
         "href": "https://itunes.apple.com/gb/app/facebook/id284882215"
       },
       {
          "type": "application/octet-stream",
          "href": "http://apps.microsoft.com/windows/en-gb/app/facebook/add3d66a-358d-4fe2-be68-8a3f934e9ea1"
       },
       {
          "type": "application/vnd.android.package-archive",
          "href": "http://www.amazon.co.uk/Facebook/dp/B0094BB4TW/"
       },
       {
         "type": "application/x-webrunner"
         "href": "https://apps.ubuntu.com/cat/applications/prism-facebook/"
       },
       {
         "type": "application/octet-stream",
         "href": "http://appworld.blackberry.com/webstore/content/680/"
       }
    ]
  }

That's maybe a bit odd because the URL doesn't point to an alternate app manifest or even the app itself, but a web page which describes an alternate app. That's maybe the best we could do given that non-web apps don't tend to have web URLs!

Hopefully this example also illustrates how badly this scales.

Alternatively, implementers could add vendor-prefixed properties to the manifest for this purpose, using whatever identifiers they like.

**Comment by alxlu** [comment]
This could be good for avoiding some user confusion as well. If this is included in the manifest it would help with a scenario where users end up installing both the native app and 'pinning' the hosted app.

>That's maybe a bit odd because the URL doesn't point to an alternate app manifest or even the app itself, but a web page which describes an alternate app. That's maybe the best we could do given that non-web apps don't tend to have web URLs!

I agree that it is a bit odd. However, on several platforms, loading the web url triggers the actual app store to launch. This still puts the user on a page that describes the app, but I don't necessarily see this as a bad thing when it comes to installing a native app.

**Comment by marcoscaceres** [comment]
On March 7, 2015 at 2:18:21 AM, Ben Francis (notifications@github.com) wrote:
> >
> This sounds bad for the web as it risks further fragmenting the  
> web into multiple walled gardens of content. 

It's the reality, tho. Please go and check Alexa's top 100 on iOS (and probably on Android): the majority of web apps are door slamming. Also, pretending the web is good enough by not providing this capability, when the Web is clearly not right now, doesn't help end-users (and just leads to either proprietary solutions to address this problem, as is currently done by Microsoft and Apple, or developers themselves doing the doorslam - or a combination of both, which I've also seen). 

The only way to stop door-slams is to make a better Web platform (i.e., developers not bothering to make a native alternative because "the Web is that good") - but, we are nowhere near close to that yet (if ever!): thus, allowing developers to easily link to their native alternatives seems fine. It's not a "one or the other" thing. Web apps and native apps have always co-exsisted - hell, a browser is just another native app that makes use of a webview, after all. The ultimate goal here is making more powerful webviews and getting the browser chrome out of the way. 

Let's play nice with native apps. Let's show them the <3 they deserve because, today, they really do make phones, tablets, and computers really really awesome to use (much more than a lot of web apps can do ... heh, listen to me ... I'm such a sell out, but it's true :)). 

> Whether or not to  
> include this in the spec probably comes down to what is the lesser  
> of two evils:
> a) Putting up with the current slam-door approach of mobile web  
> sites which force

Few will "force" a user to download an app (I've only seen Pandora do this... probably Spotify does this too). Most provide a web interface alternative.  

> users to download a non-web app based on a UA  
> string by refusing to display, and the use of proprietary meta  
> tags.
> b) Adding something to the web manifest spec which is explicitly  
> not to do with web apps and is intended to draw users away from the  
> web.

In b, a user could choose in the UA: "never show me native alternatives". That seems like a good alternative to me. 

>  
>  
> I actually quite like Android's:
>  
> except that the href attribute points to a non-web "hypertext  
> reference" with a proprietary URL scheme.
>  

Linking to alternative schemes is fine, and works well bridging the Web/native divide. 

> If we wanted to add something similar to the manifest to link to  
> alternative apps, ideally the alternative app would have a web  
> URL and a Content Type:

Content types are discriminatory hints, they don't mean anything. In particular, how would iOS know which link to provide given these three have the same content type: 

> "type": "application/octet-stream",
> "href": "https://itunes.apple.com/gb/app/facebook/id284882215"  
> },
> {
> "type": "application/octet-stream",
> "href": "http://apps.microsoft.com/windows/en-gb/app/facebook/add3d66a-358d-4fe2-be68-8a3f934e9ea1"  
> {
> "type": "application/octet-stream",
> "href": "http://appworld.blackberry.com/webstore/content/680/"  
> }

The only way would be to sniff the "itunes.apple.com" part of the URL (hence the `type` serves no purpose). Keying off the os would be better. It would also make this much easier to use, rather than having to look up weird MIME type strings.   

> That's maybe a bit odd because the URL doesn't point to an alternate  
> app manifest or even the app itself, but a web page which describes  
> an alternate app. That's maybe the best we could do given that  
> non-web apps don't tend to have web URLs!

They are links to the store page - not to the app. You don't just install apps: you first check them out, see if it's the right one (or maybe check for cheaper/higher-rated alternatives), then install them.  

> Hopefully this example also illustrates how badly this scales.  

I think discriminating on os type might be fine. This scales badly no matter what, so the following would be fine too:

```JSON
{
   "related_applications": { 
      "ios": {...},
      "android": {...},
      "windows": { ... }
   }
}
```

It's just a sad acceptance of the current reality (with the problem that those OS and store links could easily break, and it's pretty sad for longevity). But whatever, it would get the job done and allow end-users to complete whatever task/thing they are trying to do with the best tool available to them (be it a web app or a native app).  

> Alternatively, implementers could add vendor-prefixed properties  
> to the manifest for this purpose, using whatever identifiers  
> they like.

If it was only one vendor wanting this, then absolutely this should be a prefixed thing. However, the feedback I've received is that there is enough overlap between vendor solutions - and enough vendor interest - that a standardized alternative makes sense.

**Comment by marcoscaceres** [comment]
On March 7, 2015 at 5:12:46 AM, Alex Lu (notifications@github.com) wrote:
> > I agree that it is a bit odd. However, on several platforms, loading  
> the web url triggers the actual app store to launch. This still  
> puts the user on a page that describes the app, but I don't necessarily  
> see this as a bad thing when it comes to installing a native app.  

Neither do I - it seems like a good thing. What would be bad is if you ended up at a fake or wrong store. 

The UA would need to somehow verify that URL is actually for a real store (and maybe for a real app).

**Comment by marcoscaceres** [comment]
Just gonna put this here: http://idontwantyourfuckingapp.tumblr.com

**Comment by mounirlamouri** [comment]
What about having the id instead of the full URL?
The Google Play Store has something like "com.foo.bar". The iTunes store has some "idXXXXXXX". Those ids might be more long terms than URLs. UAs could even have ways to direct to the store that matches the user's location.

Note also that maybe instead of "android" and "ios" we could have "play" and "itunes". The name of the store might be better than the name of the platform given that there can be more than one store per platform. For example, the Firefox Marketplace could be listed in some platforms, or Amazon on Android.

**Comment by alxlu** [comment]
>What about having the id instead of the full URL?
The Google Play Store has something like "com.foo.bar". The iTunes store has some "idXXXXXXX". Those ids might be more long terms than URLs. UAs could even have ways to direct to the store that matches the user's location.

That seems to be how AppLinks.org does it too. But if a new vendor decided to show up, all of the UA's would need to change to accommodate it. That being said, if we are going to be checking to make sure it is a valid URL anyway then I would agree that ID's would better than URLs.

Have the URLs for the different Stores ever been broken? I was under the impression that whenever a new URL format surfaced, the Stores still generally support the old URL format as well.

**Comment by anssiko** [comment]
"related_applications": [
    {
      "vendor": <vendor name, such as "itunes">,
      "id": <uniquely identifies the app for the vendor, could be any string, UUID, ID, URL>
    },
    {
    // ...
    }
 
@kenchris and I think it is probably better to not require the `id` to be an URL that can be navigated to, just an `id` that is understood by the `vendor` is enough.

Quickly looking at the state of things, the current vendors use the following formats for `id`:
* iTunes `id284882231`
* Play `com.foobar.appname`
* Windows Store UUID
* Firefox OS Market just uses the plain application name, such as `facebook-1` or `bing-maps`
* Chrome Web Store `lkbhppfbabandkdmgjmifahoabeodiep`
* Amazon App Store for Android `B00QW8TYWO`

This seems to be somewhat aligned with @mounirlamouri's thoughts.

From @slightlyoff's proposal, I'm wondering if the order should have a significance?

> To accommodate all of these situations, the list is ordered based on developer preference. If and "android" or "iOS" entry occurs before the "web" (or default "web") entry and is appropriate for the UA to offer, an "install banner" might be shown, using the information provided in the manifest to bootstrap the offer process.
>https://github.com/slightlyoff/AppInstallImprovements/blob/master/explainer.md#offering-related-applications

**Comment by slightlyoff** [comment]
These are my proposals, so I feel I should chime in with a few points:

1.) I don't think this is anything more than crappy-header de-crufting. This stuff is already in the web. This lets us move it out of precious `<head>` bytes and into a single location. Doing prefixed stuff inside the manifest hardly helps
2.) part of the goal is to put the slam-door prompting that @marcosc and I hate in (more tasteful) UA-controlled UI. This will help us de-cruft the web as webmaster advice can ever-more-forcefully require that they use the "supported" mechanism instead of ad-hoc slam-doors.

The second point can't be over emphasized. I think everyone wants to get rid of crappy full-page prompts and this will help. For instance, once developers move to it, the Chrome mechanism for showing the prompt will use the same engagement criteria for the web page as the offer for the web app will use: never on the first visit, only once a user re-visits a few times in a week, and not again for some months once swept away.

Regarding contents of the list, I'm open to pretty much anything that works.

**Comment by marcoscaceres** [comment]
@mounirlamouri, will you put together a proposal for this?

**Comment by mounirlamouri** [comment]
I still have two concerns:
* the discussions around ```related_applications``` did not provide a way for the developers to say that they would prefer their web app to be installed instead of a native app.
* is anyone except for Chrome interested by that feature? Given that it is fine per Manifest rules to extend the Manifest, if Chrome is the only browser interested to do anything with this, maybe it should stay a chrome property?

Regarding the first question, what about having ```preferred_platforms``` that would accept ```web``` as an entry:
```js
"preferred_platforms": [{
  "vendor": "play",
  "id": "foobar"
}, {
  "vendor": "web"
}]
```

It would put the Play Store application above the Web version of the app if installation had to happen. WDYT?

**Comment by alxlu** [comment]
>the discussions around related_applications did not provide a way for the developers to say that they would prefer their web app to be installed instead of a native app.

I believe that part is addressed here:
https://github.com/slightlyoff/AppInstallImprovements/blob/master/explainer.md#offering-related-applications

**Comment by marcoscaceres** [comment]
> the discussions around related_applications did not provide a way for the developers to say that they would prefer their web app to be installed instead of a native app.

I don't know if this is really about preference, but about user choice. If the developer really wants one options over another, they have the choice to: 

 1. Not include the `related_applications` code
 1. door slam
 1. gently indicate to the user that one application provides a better experience than another choice (e.g., Amazon.com). 

> is anyone except for Chrome interested by that feature? Given that it is fine per Manifest rules to extend the Manifest, if Chrome is the only browser interested to do anything with this, maybe it should stay a chrome property?

In their customary way, Apple has expressed interest in this feature.

About `preferred_platforms`, I'm not understanding why this is about preference rather than choice?

**Comment by owencm** [comment]
As alxlu points out, Alex's doc says "to accommodate all of these situations, the list is ordered based on developer preference." so sites could list web above native to indicate their preference. I think that solves your issue Mounir, let me know if it doesn't.

Given that solution, the last question is whether this should remain as a chrome property. I hope that other browser vendors that currently use proprietary metatags will swap in the future, so I'd prefer we leave it as `related_applications` as I find it easier to imagine Apple parsing that in the future than I can something like `chrome_related_applications`, and a world where we have the same list duplicated with different prefixes isn't very appealing to me.

**Comment by kenchris** [comment]
This seems like a generic things that we want other vendors to supports, so I think it is better to attempt to get it right here before people start shipping something.

**Comment by benfrancis** [comment]
See also https://github.com/slightlyoff/AppInstallImprovements/issues/5

**Comment by benfrancis** [comment]
Or should I say, smb://ben@tola.me.uk:445/files/my_github_comments.cab (hope your user agent can read that)

**Comment by benfrancis** [comment]
OK, I've been racking my brains for a way that this could be done in a way that doesn't really suck. First I started with a vendor prefix for each vendor:

```
"android_alternate": {
   "href": "https://play.google.com/store/apps/details?id=com.facebook.katana"
},
"apple_alternate": {
    "href": "https://itunes.apple.com/gb/app/facebook/id284882215"
},
"ms_alternate": {
  "href":  "http://apps.microsoft.com/windows/en-gb/app/facebook/add3d66a-358d-4fe2-be68-8a3f934e9ea1"
}
```
Because there isn't a standard way to identify non-web apps, each vendor could extend this with whatever metadata they need. But vendor prefixes kind of suck...

Then I thought maybe a URL is sufficient to describe a non-web app by pointing at its app store URL (as has been suggested), and the store and ID could be parsed from the URL. So I started trying to re-invent HTML link relations in JSON, which could be used for lots of things, including pointing to a "related" page on an app store:
```
    "linked_resources": [
      {
        "rel": "alternate",
        "hreflang": "fr",
        "href": "http://facebook.fr/manifest.json"
      },
      {
        "rel": "describedBy",
        "href": "https://marketplace.firefox.com/app/facebook-1"
      },
      {
        "rel": "related",
        "href": "https://play.google.com/store/apps/details?id=com.facebook.katana"
      }
    ]
```
But, well that adds a lot of cruft to the manifest specification and is a bit over-engineered.

So then I sat scratching my metaphorical beard. If only there was a standard way to mark up linked data about a software application in JSON, which is suitable for user agents and search engines to parse, and which wouldn't require us to fill the "Manifest for web application" specification with data about something which isn't a web application.

Then I realised, there is! Ladies and gentlemen, I present the SoftwareApplication schema from schema.org [1].

This is a schema to mark up linked data about a software application, can be encoded in JSON in a W3C recommended way using JSON-LD [2], was designed specifically for search engines/user agents to parse, and Google even helped define it!

A simple example might be:

```
"linked_data": [
  {
    "@context": "http://schema.org",
    "@type": "SoftwareApplication",
    "operatingSystem": "Android 3.0",
    "installUrl": "https://play.google.com/store/apps/details?id=com.facebook.katana",
  }
]
```

but the schema includes many more properties if the vendor needs them.

The beauty of this solution is that all the manifest specification needs is a hook to define any type of linked data related to the web application (there was actually previously text in the spec which mentioned JSON-LD as an extension mechanism), and the rest can be documented elsewhere. For example, Google, Apple or Microsoft's developer documentation can describe how to mark up a software application for their platforms in JSON-LD, such that search engines and user agents can parse it from the manifest.

What do you think?

1. https://schema.org/SoftwareApplication
2. http://www.w3.org/TR/json-ld/

**Comment by kenchris** [comment]
It seem like a lot of tedious stuff to write for no real gain, and as discussed before, we would like to avoid using actual links and just use ids instead.

**Comment by benfrancis** [comment]
Not having to fill the "manifest for web application" specification with vendor-specific data which has nothing to do with a web application seems like a pretty big gain to me. And there are lots of other potential use cases for the JSON-LD hook.

As for ID, the schema has you covered...

```
"@id": "com.facebook.katana",
```

**Comment by kenchris** [comment]
I see this feature as a pretty important and core one that many would want, so defining a "vendor" and "id" field which values are defined externally, seems totally fine with me and something that I think we should do.

JSON-LD has so many different ways of doing similar things, like you pointed out, I can use @id or installUrl... I am afraid that that will just lead to more mess like with meta tags. Like some will use a store name, others will use operation system name, some will use url, some will use id - and users will get confused.

I definitely see JSON-LD useful for adding other meta info such as author, repo url etc, I just think this is such a core feature, which is a minor addition to the spec and which can be done in one consistent way.

**Comment by marcoscaceres** [comment]
@benfrancis, please don't waste cycles on this. @mounirlamouri will put together the proposal based on what Google is likely to implement. We can then review that.

**Comment by marcoscaceres** [comment]
Closes via https://github.com/w3c/manifest/pull/344
