### ISSUE TITLE
Are "hosted apps" in scope?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#340]
At least one of the features being defined (#161) in this spec is primarily of value to "hosted apps": that is, a web application that a vendor has pre-installed on a device (through, for example, a "marketplace"), but potentially has never been actually run. 

Question for implementers: when we started this process, we ruled out hosted apps as being in scope for this specification. Is it time to revisit "hosted apps" being in scope of this specification?

If yes, then what other things do we need to add. We had already defined CSP, for instance: 
https://github.com/w3c/manifest-csp 

cc @dvonlehman @alxlu, @mounirlamouri, @kenchris, @anssiko, @benfrancis, @skddc .

**Comment by benfrancis** [comment]
That isn't what I understand as "hosted apps", hosted web apps are just web apps which have a real URL on the web, all web apps with a W3C web app manifest are currently hosted apps by that definition.

Whether we should have an installation API so that an app store type app can install other apps without the user visiting them first is a separate question.

Pre-installing apps is probably completely vendor specific and out of scope of this specification.

**Comment by skddc** [comment]
Agree with everything @benfrancis just said.

**Comment by dvonlehman** [comment]
My definition also matches with what @benfrancis said. This is consistent with [how Amazon defines hosted apps](https://developer.amazon.com/public/solutions/platforms/webapps/docs/differences-between-packaged-and-hosted-apps) in regards to their support for HTML5 apps in their app store. 

_A hosted app is an application whose assets are hosted on a web server. Clients connect to the host and download the app's assets to their device before being able to run the app._

Advantages over "packaged apps" are:
* Hosted apps can be complete applications with server-side and client-side code.
* Hosted apps can be updated immediately. Customers always get the latest code.
* Hosted apps provide the same experience (and typically the same code) for customers as on your web 
site.

Is this definition of "hosted apps" supported by the manifest spec?

**Comment by jmajnert** [comment]
> If yes, then what other things do we need to add.

I'd say permissions are still missing, but I'm not sure this is a subject we want to get into now.

**Comment by kenchris** [comment]
I think the problem is not supporting hosted apps, but allowing people to somehow create a manifest for an app that is not hosted on the apps' origin domain.

This could allow people to package up (for their store or existing stores, like create an APK) hosted apps.

For Crosswalk, we allow people to package local web apps into APKs using the manifest and upload them to the Play Store. We have gotten requests that some vendors would actually like to package their own hosted apps (so they can update the content on demand and still make it available offline with service worker). I have suggested that they could just add a manifest to the web page itself, but apparently that is a problem for some a @PaulKinlan pointed out.

As far as I understand from the MWC presentation, Microsoft will also use the manifest for web apps in the Windows 10 store. It would be sad if that had to be limited to packaged apps (local content) and not allow hosted apps.

**Comment by jmajnert** [comment]
@marcosc - please correct me if I'm wrong - your question actually refers to applications that are already installed (preinstalled, or whatever), but whose code has never been run on the device?
If so, then I think you abused the notion of "hosted app" :-)

You are asking for propositions of features that would be useful in the specific scenario where the UA/device processes the manifest file before it has the chance to load the app itself:
* preinstallation
* app stores pushing manifests for third party apps (not currently supported)
* installation from a local package
?

**Comment by benfrancis** [comment]
@kenchris
> I have suggested that they could just add a manifest to the web page itself, but apparently that is a problem for some a @PaulKinlan pointed out.

I think I missed this, what's the reason that this is a problem for people?

> As far as I understand from the MWC presentation, Microsoft will also use the manifest for web apps in the Windows 10 store. It would be sad if that had to be limited to packaged apps (local content) and not allow hosted apps.

What is it that you think would prevent Microsoft featuring web apps which use the W3C manifest in their store? Is it that there's no install API so that they'd have to have an "open" button instead of an "install" button? Would be really good to hear from Microsoft on their use cases there.

**Comment by jmajnert** [comment]
> Is it that there's no install API so that they'd have to have an "open" button instead of an "install" button?

I don't think this would be a problem for vendor-locked UA and app store.

**Comment by alxlu** [comment]
>As far as I understand from the MWC presentation, Microsoft will also use the manifest for web apps in the Windows 10 store. It would be sad if that had to be limited to packaged apps (local content) and not allow hosted apps.

Yes, we are looking to provide JSON manifest support. If anything, based on the current state, it seems like it will be easier to use the manifest for hosted apps than for packaged apps for us.

>What is it that you think would prevent Microsoft featuring web apps which use the W3C manifest in their store? Is it that there's no install API so that they'd have to have an "open" button instead of an "install" button? Would be really good to hear from Microsoft on their use cases there.

If I'm understanding the question correctly, since our Store is it's own 'app' and not run in the browser, we don't necessarily need an installation API to make it work.

**Comment by kenchris** [comment]
@alxlu you mean hosted apps, "bookmarked" from the browser? or hosted apps in your store?

In Crosswalk we currently use the manifest for packaging local apps (no hosted ones yet) which people submit to the Google Play store. That works fine for us.

You you explain how you are currently imagining using the manifest? and where it falls short and if there is anything we can do to help you?

**Comment by benfrancis** [comment]
> Yes, we are looking to provide JSON manifest support. If anything, based on the current state, it seems like it will be easier for us to use the manifest for hosted apps than for packaged apps.

That is the intended use of the W3C web app manifest, so that makes sense.

> If I'm understanding the question correctly, since our Store is it's own 'app' and not run in the browser, we don't necessarily need an installation API to make it work.

OK, interesting. So Microsoft does have use cases for web apps which may be "installed" from an app store before being loaded in the browser. Windows 10 will just use a platform-specific API for installing the app like Firefox OS currently does?

That seems to answer what I think @marcosc's original question was, and has potential implications for Service Worker integration. If a Service Worker is not defined in the manifest to be registered at install time, then there's a risk that the app may not work offline until the second time it is launched.

**Comment by kenchris** [comment]
I don't get why they would need any API for installing. People can just upload the app incl a manifest.json to the store, or like Crosswalk does, run a command line tool which takes the sources + manifest.json, wraps it in a package which then can be uploaded to the Google Play store.

**Comment by benfrancis** [comment]
@kenchris:
> I don't get why they would need any API for installing.

The Windows Store app presumably uses an internal API in Windows to install the web app in the OS, I'm not suggesting that they need a web API for that if the Store app is not a web app.

> People can just upload the app incl a manifest.json to the store, or like Crosswalk does, run a command line tool which takes the sources + manifest.json, wraps it in a package which then can be uploaded to the Google Play store.

That is not how the spec says a manifest should be obtained [1], a web app has a manifest URL on the web which is used for retrieving the manifest. If you want to use the same manifest format for packaged apps then that's up to you, but that isn't a web app and as I understand it is outside the scope of this spec.

However, Microsoft's use case does sound like a web app using a web app manifest hosted at a manifest URL. @alxlu Can you confirm that the manifest would be hosted by the web apps themselves, not packaged inside an app package uploaded to the store?

1. http://w3c.github.io/manifest/#obtaining

**Comment by alxlu** [comment]
>@alxlu you mean hosted apps, "bookmarked" from the browser? or hosted apps in your store?

Hosted Apps in our Store. The "bookmarking" from the browser is something we are still exploring as an option. If we do enable "bookmarking" it will very likely come after Store support.

>However, Microsoft's use case does sound like a web app using a web app manifest hosted at a manifest URL. @alxlu Can you confirm that the manifest would be hosted by the web apps themselves, not packaged inside an app package uploaded to the store?

Our hosted apps are part of our Universal App Platform, so they are actually packaged and uploaded to the Store just like all our other types of Universal Apps. However, we are exploring different app submission processes&mdash;particularly ones that involve a user potentially just submitting a url as opposed to uploading a package. Automatically keeping the manifest in our Store package in sync with the remote manifest is something we would like to explore as well.

**Comment by boyofgreen** [comment]
I know this is a bit of an old issue, but I wanted to put my perspective on the table.  Note, I work with Alexlu in the Dev role at Microsoft around this.  RIght now we see hosted apps and packaged apps as two different app types.  Although the technical implementations may be very different now, I believe they are moving towards the same thing.  The difference will be a user installs from the store vs installs from the web.
  For a Dev, implementation should be the same.  Create a manifest, and add it to your website.  At MS we are starting on the store end, and are moving towards the browser end.  I know others are starting (rightfully so) from the browser.

**Comment by marcoscaceres** [comment]
Closing the loop on this, basically https://github.com/w3c/manifest/issues/340#issuecomment-85175804 defines what we generally understand to be a hosted app (i.e., the term is redundant, because, as @benfrancis pointed out, all web apps are hosted apps).
