### ISSUE TITLE
Add requirements when the Manifest is used by crawlers

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#343]
One benefit of the Manifest is that it is discoverable by crawlers but I realise that we do not actually even mention that in the specification or use cases related to it. Also, we list no requirements for crawlers like folliwng robots.txt.

**Comment by kenchris** [comment]
+1

**Comment by jmajnert** [comment]
> Also, we list no requirements for crawlers like folliwng robots.txt.

I agree with mentioning crawlers in use cases and introduction to the spec. But can we define requirements for crawlers? Isn't this out of scope?

**Comment by marcoscaceres** [comment]
On Wednesday, March 25, 2015, Janusz Majnert <notifications@github.com>
wrote:

> Also, we list no requirements for crawlers like folliwng robots.txt.
>
> I agree with mentioning crawlers in use cases and introduction to the
> spec. But can we define requirements for crawlers?
>
>
Those requirements should come from at least 1 search provider. Plenty of
Google folks around, which is great (and google is already doing a good job
at surfacing mobile friendly web apps in their results).

I will do my best to find some from Yahoo! On the Moz side, since they are
our primary search provider (in North America) and would expect them to use
this at some point.


> Isn't this out of scope?
>
I would say it's in scope.

**Comment by marcoscaceres** [comment]
> Also, we list no requirements for crawlers like folliwng robots.txt.

This seems outside the scope of this document. Robots.txt already defines general rules for spiders trying to access resources. 

However, I'll add a search engine and a browser as examples of user agents. 

If there are specific requirements for search engines beyond processing manifests in the manner specified in the spec, then I would like to hear them.
