### ISSUE TITLE
Support for Actionable Notifications in the manifest

### ISSUE THREAD

**Issue by tikurahul** [w3c/manifest#347]
### Introduction

I wanted to add support for actionable notifications for a web app, that can be discovered using its manifest. The use case behind this is to be able to support applications like the [Physical Web project](https://github.com/google/physical-web)**. As we have more sensors (or IoT devices) which essentially expose simple services, it is not scalable to have to install an app for each and every IoT device or sensor being used. This is why the Physical Web project is using `Bluetooth LE` and `mDNS` to expose services offered by these devices via `URL's` to web-apps that can be discovered using a common protocol.

### Why and How

The manifest should be able to support actionable notifications as an enhancement, for quick actions. Quick actions are links to more things (URL's or deep links).They give fast 1-click access to frequently used features in the web-app (without having to visit the web app again). These 1-click actions could then be exposed via by the user agent using Notification panels or custom UI components; thus making them readily available.

The Website's manifest file can include quick actions that are supported by the site.
This is what the the `payload` in the manifest could look like:

    [
      {
        "icon": "icon_url",
         "title": "The Title of the actionable Notification",
         "link": "deep_link_or_url"
      },
     {..}
    ]

A good example for quick actions could be turning smart lights `On` and `Off`. 

**Related discussion in the [Physical Web] (https://github.com/google/physical-web/issues/307) project.

**Comment by benfrancis** [comment]
@tikurahul This is interesting, Mozilla is discussing some features for Firefox OS which could create similar use cases for marking up actions which an app can carry out.

However, I'm not sure I fully understand why the app manifest is a good place to add metadata for the particular use case you're describing.

My understanding of the Physical Web project is that you should not need an app per "thing", but that things broadcast URLs which allow users to carry out actions on those things. As discussed in the issue you reference https://github.com/google/physical-web/issues/307 a good way to do this might be for a thing to broadcast a URL which returns metadata using a schema describing the thing [1] and actions [2] which can be carried out on that thing. A user agent can then provide a UI to carry out actions on a thing, but you wouldn't want to have to install an app for every thing in order to do that. Therefore I'm not sure the app manifest is the right place for this metadata?

I wonder whether "actionable notifications" are more of a use case for the Web Notifications API? Perhaps you could embed an action [2] in the body of a notification in order to make that notification actionable? Or, a user agent could use its notifications UI to simply display actions discovered for nearby devices to the user, without needing to use the Web Notifications API.

In this case where the interaction doesn't need to happen through an installed app I'm not sure the app manifest is the right place for that metadata, but for other cases where an app wants to register itself as handling a particular type of action when it is installed, I think there are potential use cases that fit the app manifest. For example, a web search app might want to register as handling a "SearchAction", a communications app might want to register as handling a "CommunicateAction" or yes, a smart home app may want to handle a "ControlAction". This is more like the use cases of Web Activites/Web Intents.

1. http://schema.org/Thing
2. http://schema.org/docs/actions.html
3. http://www.w3.org/TR/notifications/
4. http://schema.org/SearchAction
5. http://schema.org/ControlAction
5. http://schema.org/CommunicateAction

**Comment by tikurahul** [comment]
Thanks @benfrancis for your comments. I understand now that the purpose of the web app manifest is primarily to support metadata pertaining to the *installing* of web apps. 

I had a few questions, which might be beyond the purview of this project, but I would be grateful if you could answer them. I like the idea of supporting an endpoint that can be used to describe the *thing* and *actions* pertaining to it. Looking at the [http://schema.org/Thing](http://schema.org/Thing) my understanding is there is no standard way of discovering more than one *potentialAction* for a given *thing* ? Is that correct ? 

Do you think support for these actions makes sense in the context of the Web Notifications API ? If the Web Notification's body exposed these types of actions, it would be awesome if the user agent supported a suitable subset (if not all) of these types of actions.
