### ISSUE TITLE
Must manifests be same-origin?

### ISSUE THREAD

**Issue by jyasskin** [w3c/manifest#360]
https://w3c.github.io/manifest/#obtaining step 3 says 

> If the URL of _manifest link_'s `src` attribute is not same origin as its owner `Document`, then … terminate this algorithm.

However, https://w3c.github.io/manifest/#content-security-policy says

> The `manifest-src` and `default-src` directives govern the origins from which a user agent can fetch a manifest.

Which is it?

**Comment by benfrancis** [comment]
I noticed the same thing yesterday @jyasskin. Since the same-origin restriction was added the CSP part of the spec is basically redundant.

This is being actively discussed in https://github.com/w3c/manifest/issues/272 and https://github.com/w3c/manifest/pull/353 though so it's not yet clear which part should be removed!

**Comment by benfrancis** [comment]
One reason for requiring a manifest be same-origin with the web app is to prevent someone creating an "app" for someone else's content without their knowledge. Are there other ways we could prevent this which don't render manifests useless as a standalone resource?

This might be a bit of a hack but... What if "Content-Security-Policy: manifest-src self" could be used to prevent others creating apps for your content in the same way that "X-Frame-Options: SAMEORIGIN" prevents others from framing your content. e.g. :

* An application context has a manifest applied from http://evil-cdn.com/manifest.json
* The manifest contains a start_url of http://foo.com/start.html
* The application context is navigated to http://foo.com/start.html
* The HTTP response of http://foo.com/start.html contains a header "Content-Security-Policy: manifest-src real-cdn.com"
* The application context refuses to render start.html because http://evil-cdn.com/manifest.json does not match real-cdn.com

This would allow start_url could be resolved against the manifest URL instead of document URL, cross-origin manifests could use an absolute URL.

**Comment by jmajnert** [comment]
@benfrancis this looks like it might work.

**Comment by anssiko** [comment]
@benfrancis Let me try to rephrase your proposal in terms of HTTP requests and responses. Some details omitted for brevity. Correct any misinterpretations.

Assumptions made for the currently unspecified `manifest-src` directive:

* `manifest-src *` permits cross-origin manifest fetch by default (in addition cross-origin manifest fetch response must have proper `Access-Control-Allow-Origin` header set)
* `manifest-src 'self'` enforces same-origin manifest fetch
* `manifest-src real-cdn.com` allows cross-origin manifests from real-cdn.com only

Example: evil-cdn.com hosts manifest.json. foo.com indicates it trusts real-cdn.com only to deliver a valid manifest. The UA considers manifest.json served from evil-cdn.com invalid since it violates foo.com's manifest-src directive.

Request foo.com:
```
GET / HTTP/1.1
Host: foo.com
Accept: */*
```

Response:
```
HTTP/1.1 200 OK
Content-Type: text/html
Content-Security-Policy: manifest-src real-cdn.com

<html>
<head>
 <title>foo.com</title>
 <link rel="manifest" href="http://evil-cdn.com/manifest.json">
</head>
<body>
</body>
</html>
```

Fetch of http://evil-cdn.com/manifest.json fails due to manifest-src violation, response would have been:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://foo.com
Content-Type: application/manifest+json

{
 "start_url": "http://foo.com/start.html"
 ...
}
```

@benfrancis Did I get your proposal right?

**Comment by benfrancis** [comment]
@anssiko Actually I think all of what you just wrote is already covered by the Content Security Policy section in the spec http://w3c.github.io/manifest/#content-security-policy but it is currently redundant due to the same-origin restriction recently added.

What I'm proposing is that the CSP header also be used at runtime to prevent pages being rendered inside an application context with an unauthorised manifest applied.

For example, the application context of an app installed from a manifest at http://evil-cdn.com/manifest.json could not render a page from http://foo.com/index.html which included an HTTP header like "Content-Security-Policy: manifest-src real-cdn.com".

This idea is that this makes the manifest less dependent on the page it was installed from, and more of a useful resource in its own right. That allows for use cases like installing an app directly from its manifest URL (using some internal installation mechanism in the user agent).

Like with embedding web pages in iframes, the default would be that it is permitted, but a developer can opt-in to protecting their content being installed via an externally defined manifest.

**Comment by anssiko** [comment]
@benfrancis Ok, I think I got your idea. So in addition to preventing manifest fetches (that effectively prevent adding to home screen et al.), you suggest to also prevent pages from being rendered in the application context if the manifest is unauthorised?

Example of what I think you're after:
* the page is "installed" using an authorised manifest
* the page is tampered with to point to an unauthorised manifest instead
* the page is attempted to be launched in the application context
* runtime check prevents the page from being rendered

Should what follows be an implementation detail? For example, display a dialog similar to [untrusted connection](https://support.cdn.mozilla.net/media/uploads/gallery/images/2011-10-19-09-09-25-5809bb.jpg), that says e.g. "This Web Application is Untrusted", silently fallback to a regular browsing context, something else?

**Comment by benfrancis** [comment]
Sort of. It's less about a page being tampered with, and more about potential use cases where a page might not be involved in the installation process at all.

For example, if a web app were to be submitted to the Windows Store or the Firefox Marketplace by its manifest URL alone (without reference to any page), an application context could be created using that manifest without worrying that the content at its start_url is being used as an app against the author's will!

Currently the spec makes these assurances by assuming that an app will be installed from a page of the app itself and checks the start_url is same origin with that page, this alternative approach works even if a page isn't involved.

I think it could be left down to vendors whether to show an error or handle the navigation with a regular browsing context (i.e. open it in a browser tab).

The only question is whether those use cases are considered in scope for the spec or not.

**Comment by anssiko** [comment]
@benfrancis Thanks for the elaboration, that helps.

@marcoscaceres @kenchris WDYT?

**Comment by kenchris** [comment]
I think that it might work and we definitely need to support the use-case of submitting manifest.json. It sounds like MS needs it, and we personally need it for Crosswalk :-)

What about fullscreen and phishing/MITM? I guess that anyone could create an app which starts in fullscreen and embeds another site in a full viewport iframe. Can we somehow guard us against that?

**Comment by benfrancis** [comment]
Good question. Firefox OS currently prevents an application context being embedded inside a browsing context without a special permission, to prevent this kind of attack. Web content can always opt-out of their content rendering inside an iframe using an X-Frame-Options header, but maybe a more general protection is needed if this is a goal.

**Comment by marcoscaceres** [comment]
Depends on outcome of #272.

**Comment by marcoscaceres** [comment]
Fixed via https://github.com/w3c/manifest/pull/377
