### ISSUE TITLE
Support registering "actions"

### ISSUE THREAD

**Issue by benfrancis** [w3c/manifest#442]
The Ballista project has a proposal to register "actions" inside the web manifest, as a standard to replace Google's Web Intents and Mozilla's Web Activities.

https://github.com/chromium/ballista/blob/master/docs/explainer.md

This issue is to track the possibility of adding such a feature to the Web Manifest spec.

**Comment by benfrancis** [comment]
We are removing the Web Activities API from Gecko in bug [1261001](https://bugzilla.mozilla.org/show_bug.cgi?id=1261001) as part of the [B2G OS Transition Project](https://wiki.mozilla.org/B2G/Transition_Project) so we are interested in Ballista as a potential replacement, integrating with Web Manifests and Service Workers.

**Comment by mgiuca** [comment]
Hi @benfrancis. Thanks for your interest in Ballista. Indeed our current proposal does include an addition to the Web Manifest spec. (Note that we didn't reach out to standards committees yet because we're still thinking/experimenting and aren't ready to spec it.)

I'll keep contact on this issue as we move towards standardization. Let me know if there's anything you think I should be doing at this early stage to work with Mozilla or W3C on this.

**Comment by marcoscaceres** [comment]
Marking as V2 feature.

> Let me know if there's anything you think I should be doing at this early stage to work with Mozilla or W3C on this. 

Just keep us up to date on any progress or we can set up a call to chat.

**Comment by marcoscaceres** [comment]
@mgiuca, given the creation of the [Web Share](https://github.com/WICG/web-share) repo over at the WICG, I suggest we continue discussion over there. If manifests end up being part of that, we an reopen or file new bugs here.

**Comment by marcoscaceres** [comment]
Sorry, that should have included a cc to @benfrancis.... see you in the other repo 💃
