### ISSUE TITLE
Ability to detect if the current document is part of an "installed" web app

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/manifest#454]
Forked from #417 

It would be very valuable to have an API that allowed a website to know what manifest the user agent has loaded for the current scope (if any).

## PROPOSAL

Add an API to get the current manifest

Something like:

```javascript
var manifest = navigator.document.getManifest();
if(manifest){
  var startUrl = manifest.start_url;
}
else {
//No manifest loaded
}
```

## Questions

 1. Where is the right place for the API (navigator, document, other)?
 1. What happens in the case where two manifests have overlapping scope and the current URL is in that shared scope space?
 1. What properties/methods should be available on the Manifest object beyond the data members of the original JSON file? (Install date?, Install URL?, Update method?)

**Comment by marcoscaceres** [comment]
> On 18 Apr 2016, at 7:13 PM, Adrian Hope-Bailie <notifications@github.com> wrote:
> 
> Forked from #417
> 
> It would be very valuable to have an API that allowed a website to know what manifest the user agent has loaded for the current scope (if any).
> 

Before continuing, can we expand on "it would be useful" to clarify the use cases? 

Playing devil's advocate: A dev can already fetch() their manifest, so what would this provide and why?

**Comment by adrianhopebailie** [comment]
> A dev can already fetch() their manifest, so what would this provide and why?

There seems to be an assumption in a lot of the spec that a user that has the manifest installed will never visit the app other than via the new icon on their homescreen.

My reading of @felquis comment on https://github.com/w3c/manifest/issues/417#issuecomment-168700461 was that he has users hitting URLs that are part of the app but have landed there directly from links on the web. He then needs to decide if he should encourage them to install the app or not but has no way of knowing if they already have.

Two use cases/questions:

1. How does a dev know if the user has installed the manifest (and when) so they can try to force an update if necessary or encourage the user to perform the install?

1. How does the dev know which manifest the user agent has interpreted as the current manifest (if any) if the user lands on a page that is inside the scope of multiple possibly previously-installed manifest?

**Comment by marcoscaceres** [comment]
> On 18 Apr 2016, at 10:07 PM, Adrian Hope-Bailie <notifications@github.com> wrote:
> 
> A dev can already fetch() their manifest, so what would this provide and why?
> 
> There seems to be an assumption in a lot of the spec that a user that has the manifest installed will never visit the app other than via the new icon on their homescreen.
> 
Yes. It's complicated because transition between the app experience and the tabbed browsing experience may differ - and jumping into one or the other may annoy/confuse users. We just don't know yet. It's something that will take a lot of time to test and get right. 

> My reading of @felquis comment on #417 (comment) was that he has users hitting URLs that are part of the app but have landed there directly from links on the web. He then needs to decide if he should encourage them to install the app or not but has no way of knowing if they already have.
> 

If a developer needs to encourage installation, then the browser has completely failed: progressive web apps are supposed to solve this exact problem: 

https://infrequently.org/2015/06/progressive-apps-escaping-tabs-without-losing-our-soul/

It's too early for us (browser vendors) to admit defeat here. We only have two shipping UAs and I think only Chrome is making use of installability signals. 

Firefox is just now starting to lay down the infrastructure to test installability signals. But this will take at least one or two years (our Android team is tiny, and it's only me helping on the DOM side, and I barely know what I'm doing: 🐶💻)

Having said that, the "install" event is supposed to address the "did they install the app?" question - but still give users the ability to "clear cookies/storage" to make the site forget about it.

> Two use cases/questions:
> 
> How does a dev know if the user has installed the manifest (and when) so they can try to force an update if necessary or encourage the user to perform the install?
> 
The "install" event - but again, encouraging is considered absolutely a failure from a browser vendors pov: we don't want sites annoying users with "install our app" buttons and banners. 

Re updates: As noted in the other bug, we probably need a "requestUpdate()" API. We would need to work out the details. 

> How does the dev know which manifest the user agent has interpreted as the current manifest (if any) if the user lands on a page that is inside the scope of multiple possibly previously-installed manifest?
> 
I imagine one can check with the Cache API - to see which version is download, and other cache information. However, the end-user may have modified aspects of the manifest (through the browser's provided install UI). 

I think we can only really solve the scope change problem with an update API. That way, the site can request and track precisely which version is being applied without any magical/unexpected things happen in the background.

**Comment by adrianhopebailie** [comment]
> I imagine one can check with the Cache API - to see which version is download, and other cache information. However, the end-user may have modified aspects of the manifest (through the browser's provided install UI).

This raises another question. How does the developer know what the properties of the current manifest are? i.e. How do they know if the user has over-ridden some values or which version of the manifest is being used?

>If a developer needs to encourage installation, then the browser has completely failed: progressive web apps are supposed to solve this exact problem: 

>https://infrequently.org/2015/06/progressive-apps-escaping-tabs-without-losing-our-soul/ 

>It's too early for us (browser vendors) to admit defeat here. We only have two shipping UAs and I think only Chrome is making use of installability signals. 

It sounds like you're saying you want browser to intentionally make it difficult for a developer to detect how their app is being presented to the user? If not, then that suggests there are other ways they could detect this anyway so having a `getCurrentManifest()` wouldn't make the situation worse it would simply make life easier for developers with good intentions.

**Comment by marcoscaceres** [comment]
> This raises another question. How does the developer know what the properties of the current manifest are? i.e. How do they know if the user has over-ridden some values or which version of the manifest is being used?

Yes, this is private. It's none of their business if I rename they app. Just like a dev doesn't get to know what I call my bookmarks or where I store them (or what folders I use on my phone to store apps, etc.). 

 > It sounds like you're saying you want browser to intentionally make it difficult for a developer to detect how their app is being presented to the user? 

No, that's what css display-mode is for. You can also pick up the orientation. The rest is private to the user. There would need to be strong reasons to provide user modified information back to the browser, because privacy.

**Comment by adrianhopebailie** [comment]
> No, that's what css display-mode is for. You can also pick up the orientation.

That suggests that we may have developers that set application-context settings like "fullscreen" and then detect for those as a workaround for `isManifestInstalled()` right? My question then is, if there is a workaround for developers to get this why not just give it to them :smile:

**Comment by marcoscaceres** [comment]
> On 22 Apr 2016, at 7:16 AM, Adrian Hope-Bailie <notifications@github.com> wrote:
> 
> No, that's what css display-mode is for. You can also pick up the orientation.
> 
> That suggests that we may have developers that set application-context settings like "fullscreen" and then detect for those as a workaround for isManifestInstalled() right? My question then is, if there is a workaround for developers to get this why not just give it to them 
> 

We already did. We gave them the install event and are still working on the beforeinstallprompt.

**Comment by marcoscaceres** [comment]
Closing for now, as there does not appear to be any further actions needed. Pending feedback from supporting "oninstall" event.
