### ISSUE TITLE
Add optional Transition Screen member

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#478]
To enable progressive web apps to have native-like behavior, a potentially important aspect of functionality is the app or UA being able to display some sort of indication when the user has triggered a navigation.

This optional member would contain an array of images of different sizes that UAs could display between when a navigation is invoked and when the next page is ready to be displayed to the user.  

If this optional member is present, UAs could:
1. Use a platform default (ex: spinner, loading bar, hourglass or watch icon, etc.)
2. Display an image of appropriate size for their screen 

The optional member should also support some "NONE" value so that Web Manifest authors could indicate that they do NOT want the UA displaying any loading indication (as they may already be doing so in their web app.)

**Comment by marcoscaceres** [comment]
I'm not sure we need this, as we already have in the platform:

```HTML
<link rel="prerender" href="nextpage.html">
<!-- or dynamically adding the above with JS! -->
```

This allows for instantaneous pre-rendering of web pages when there is clear intent that the user is going to navigate. It also handles correctly sizing the next navigation, which wouldn't be possible with an image. Additionally, it is much more size and memory efficient than using an image, as the browser is in full control of the pre-render process (and no additional resources need to be downloaded, the existing css, and assets can be used, etc.). 

Additionally, using pre-render together with the Cache API results in lightning fast navigations. But even without pre-render, the Cache API already makes it possible to cache next pages in a very efficient manner (we are talking >100ms render times, as all resources are already available), thus transitions shouldn't be needed.

**Comment by marcoscaceres** [comment]
err, I meant "<"

**Comment by RobDolinMS** [comment]
Thanks.  I didn't think of link rel=prerender and that's a good solution when navigations are in a linear sequence (ex: Level 1 -> Level 2 -> Level 3 ...)

In a case where the navigation might not be linear (examples below), having a transition screen that the UA can display while loading the next content could be valuable.

Examples:
* A game in which a user can visit one of multiple "neighbors"
* A game in which a user can choose to play one of multiple unlocked levels
* A social experience in which a user can navigate to one of multiple "friends"
* A financial app in which a user can check the performance of one of multiple stocks/funds/etc.

**Comment by marcoscaceres** [comment]
I still think that the appropriate place to address this is within the application itself, rather than something in the manifest.

For all of the examples listed, it feels like a developer should be able to design the transition experience based on where the user is navigating from/to - rather than having a single screen that serves as the transition screen. Additionally, developers might want to not have the transition at all for certain navigations - so they would also need some means to enable/disable the transition for certain pages.  

Many transition won't require images at all: without us adding a CSS-like syntax, a transition screen would not allow a developer to control the timing and animation associated with a transition (e.g., "fade out to black over 2 seconds", or "show this image, then remove it by sliding it downwards"). It would mean that each user agent would need to decide how to transition between pages while taking that control away from developers (leading to inconsistencies across browsers). 

I would rather developers be given full control over transitions and they deal with that at the application level.

**Comment by RobDolinMS** [comment]
If a user has a good connection and/or there's not much content to load, I would expect very small delay and thus the user agent might not even need to show the transition screen.

However, if there is lots of content to load and/or the device has a low bandwidth connection, giving a web app developer some easy way to communicate that their app is loading (and has not hung) is valuable.

@marcoscaceres, you're definitely right that developers could write something like this for themselves, but offering an option as easy as adding one line to the web app manifest would lower the bar for web site developers to publish as a web app and get more native-like functionality.

**Comment by kenchris** [comment]
I am afraid that users will also believe this is the right way to do it and that their app is more complete the more they use of the manifest features. I wonder if there is a way around this, ie. calling it something like *_fallback or so

**Comment by seksenov** [comment]
I agree that the best experience would be something that the developer invests in as part of her/his web app experience. 

However, we've had feedback from developers around their existing web apps loaded in an app host rather than the browser where they'd like a loading indicator to be displayed during navigation instead of a blank page. 

Often times the developer reverts to loading their web app in a webivew and placing custom platform UI on top during navigations. We've seen that the platform offered loading indicator is enough almost all the time.

Our thought was to have the app host show the loading indicator automatically if the developer opted in through the manifest. It could be off by default and the manifest attribute would serve as a toggle.

**Comment by marcoscaceres** [comment]
> However, we've had feedback from developers around their existing web apps loaded in an app host rather than the browser where they'd like a loading indicator to be displayed during navigation instead of a blank page. 

I'm confused, as this problem is solved by service workers?: When you have a service worker in place, and resources cached, you get instantaneous loads. 

> We've seen that the platform offered loading indicator is enough almost all the time.

I'm assuming this means on Windows 10. I'd be really interested in seeing an example. I've never seen this on any other platform, which is why I'm so hesitant to include it.  

Apologies if this is obvious on Windows, I've just not experience it so it's new to me. Just trying to understand what the experience would be like (particularly if the navigation never completes or takes an excessive amount of time, or if it results in "choppy" navigations that transition between this transition screen and the next loaded page). 

> Our thought was to have the app host show the loading indicator automatically if the developer opted in through the manifest. It could be off by default and the manifest attribute would serve as a toggle.

Yep, got that.

**Comment by seksenov** [comment]
> I'm confused, as this problem is solved by service workers?: When you have a service worker in place, and resources cached, you get instantaneous loads. 

Service workers solve the problem when the content is cached but it still exists with fresh content. Take a news or shopping app as examples, in both cases there would be fresh content to be navigated to.

>I'm assuming this means on Windows 10. I'd be really interested in seeing an example. I've never seen this on any other platform, which is why I'm so hesitant to include it. 

I don't believe this is displayed automatically by any UA today but each platform has one or more UI loading indicators. I've attached an image of what the experience would look like on Windows 10. You can ignore the all red background, that should be white page or content starting to populate. What we'd like is to show and focus on is a platform chosen loading indicator.
![loadingscreenexample](https://cloud.githubusercontent.com/assets/7948683/18530251/80d81266-7a85-11e6-9f33-41b4905fe5f1.jpg)

It is fine for this to be an optional switch in the manifest. It could be on or off by default (open to suggestions) but we'd like to give developers the control to toggle the state.

**Comment by marcoscaceres** [comment]
@seksenov, I'm really really sorry, I know we are going in circles a little bit (this is not deliberate on my part and I feel terrible). But what is being proposed still doesn't make sense to me - so I'm going to see if I can clarify what is being asked. 

You state that:

> What we'd like is to show and focus on is a platform chosen loading indicator.

This is different from the OP - which wanted the UA to choose an image to be displayed in between navigations. Let's put that aside and focus on your request. 

We currently have these scenarios:

1. The application starts up and performs the first navigation (/index.html) - some kind of splashscreen is shown. Right now, for instance, Chrome on Android uses an icon and "background_color" to compose a splash screen on first navigation. Are you proposing that instead, if this is present, a platform-specific loading indicator would be shown? 
1. When user navigates from index.html to page2.html. The developer can do one of the following: 

  2.1 speculative request that the browser prerender page2.html.
  2.2 Have page2.html stored and served from the service worker cache. 
  2.3 Load the page from network (which can take time in, for example, "Lie-Fi").

In the case that 2.3 occurs (or 2.1 and 2.2 don't complete in a timely manner - say, 1 second), and the developer has set this flag, the user agent would compose a "background_color" + a platform-specific spinner and show that until first paint. 

Did I get that right? 

If so: I'm not a huge fan of this, to be honest. I'd prefer if developers just fix their apps to show something quickly on their page (specially because they have the capability to do that via 2.1 or 2.2 above). However, I'd like to hear other opinions.  

@mounirlamouri or @jakearchibald, can you kindly please chime in?

**Comment by kenchris** [comment]
I guess you could even create a simple library, which could do all of the above and even store a loading screen with spinner in the SW cache and quickly show that between loads, or something similar.

**Comment by marcoscaceres** [comment]
@kenchris, that's also what I think as well. I'm worried about adding something that could so easily be done with a couple of lines of JS/CSS.

**Comment by jakearchibald** [comment]
I'm into fixing the problem mentioned in the OP, but I agree that the manifest isn't a great place to solve it.

With service worker, you get near-instant navigations, even if the body content is coming from the network. Check out jakearchibald.com in the latest Chrome - the header of the page is stored locally, but the rest streams from the network.

What this doesn't give us is a nice transition between states, and it bugs me that developers end up reimplementing the whole navigation system just for transitions.

I'd love for us to look at navigation transitions again, using http://cwiiis.github.io/gaia-navigator/ as a starting point (I haven't dug into the proposal too much, so it might be perfect as it is). 

@RobDolinMS @seksenov if we were to try and get a cross-browser group together to think about this, who should I keep in the loop at MS?

**Comment by benfrancis** [comment]
CC @Cwiiis

**Comment by RobDolinMS** [comment]
>@RobDolinMS @seksenov if we were to try and get a cross-browser group together to think about this, who should I keep in the loop at MS?

@jakearchibald for MSFT, loop-in me and Kiril @seksenov

**Comment by RobDolinMS** [comment]
@Cwiiis What is the state of http://cwiiis.github.io/gaia-navigator/ ?

**Comment by marcoscaceres** [comment]
@RobDolinMS, consider it an unofficial strawperson proposal for now (Google has also made similar proposals in the past). However, certainly something we need tho - but page transitions will be something we will need to get the CSS working group to solve.

**Comment by Cwiiis** [comment]
> @Cwiiis What is the state of http://cwiiis.github.io/gaia-navigator/ ?

I haven't had time to work on it. I got some feedback about it, most of which I think I dealt with, and there was some interest internally to implement, but nothing came of it. You can see an incomplete shim of it demonstrated here: http://chrislord.net/files/mozilla/gaia-navigator/examples/

**Comment by marcoscaceres** [comment]
@Cwiiis, maybe a good candidate to move to the WICG?

**Comment by RobDolinMS** [comment]
After discussion with @Seksenov, I think we have a simpler solution and have proposed it in Issue #504
