### ISSUE TITLE
Too many icons

### ISSUE THREAD

**Issue by photopea** [w3c/manifest#587]
I think that the current state of the specification is unnecessarily complex.

You can define multiple icons, and you also have to manually type the size of each icon in the manifest. 

First. I think the size should be removed. The size can be obtained by the user-agent by actually downloading the icon. In time of streaming of 4K videos it should not be a big deal.

Next, I think that multiple icons are not necessary. The author should provide just a single icon in any (but usually high) resolution and the user agent will adapt it according to the actual needs of the device. Having the possibility of multiple icons is confusing. App makers will not be sure which dimensions should they have. And user agents will be confused, which resolution to use, when the required is not present. And trying to define a "must-have" icon of e.g. 128x128px is also wrong from a long-time perspective.

For example, I use 512x512 px icon for my webapp Photopea: https://www.photopea.com/pp_icon.png , which is just 10 kB.

**Comment by patrickkettner** [comment]
is there something preventing you from using a single icon like you suggest for your own needs?

**Comment by mgiuca** [comment]
I don't think those are valid simplifications.

* You need to specify the icon size in the manifest so the UA doesn't have to download them all to find out which one matches the desired size. "In time of streaming of 4K videos it should not be a big deal." isn't a useful argument; I should not require a connection capable of streaming 4K videos in order to visit a web page. On bad connections, it's vital that we download as little as possible when the user is simply browsing from page to page. Kilobytes matter.
* User agents can scale icons but the best results will be achieved when the app specifies its own icons at the right sizes. User agents won't be confused; they'll just choose the best size and scale if necessary.

I take your point, though, that developers will be confused about what sizes to include. Right now we aren't very clear on this. I'd like us to come to a standard set of icons that are recommended (across all browsers, not by each individual browser vendor). That recommendation could change or expand in the future but it would be helpful to have one.

**Comment by photopea** [comment]
@patrickkettner as the author of the website, I will be confused, which size of the icon should I use. When inserting multiple sizes is possible, I would deduce, that the user agent can not scale icons, so I would be afraid, that if I miss some size, there would be some "N/A icon" used instead.

@mgiuca  I am not suggesting to download several icons and choose the right size. Later, I suggest using just a single icon, so just that single icon should be downloaded. I think that in 99% of cases, users will use just diferent resolutions of absolutely the same icon. This task can be performed by the user agent in a fraction of a second. So all you do is making the life of site authors harder, and browser makers will be confused too, what to do with so many icons.

"I'd like us to come to a standard set of icons that are recommended" - I do believe, that this is the way to hell. Site author would create the largest of them and then he would use some special software to scale it down (it is a waste of his time).

**Comment by kenchris** [comment]
You can use a SVG for set sizes to "any" - then you only need to supply one icon. If you want to optimize specific sizes (because the logo becomes to blurry and need pixel optimizations at low sizes) then add a new PNGs as well for small sizes.

All that is possible today from a spec point of view. If it doesn't work in your browser of choice, please file bugs.

**Comment by mgiuca** [comment]
I think if you want to you (and don't want to use SVG as Ken suggests) you can just supply a 512x512 PNG and let the UA downscale as necessary.

The spec just gives additional options for developers who want to optimize the download (by letting users download smaller icons instead of a large one that gets downscaled) or fine-tune the details of the icons at low resolutions (which is often necessary for icons to look good). We shouldn't remove those options just because some developers don't want to take advantage of them.

**Comment by marcoscaceres** [comment]
Closing, as the question has been answered by @kenchris and @mgiuca. @photopea also check out Chrome dev tools "application" panel, where you can see your icons being displayed from the manifest. See also lighthouse, in Chrome dev tools, which suggests the appropriate icon sizes.

**Comment by photopea** [comment]
Guys, have a look at this: https://mxb.at/blog/how-to-turn-your-website-into-a-pwa/

The author is recommending some web service, that will convert a large icon into multiple sizes. I am sure, that 99% of users will make different size versions of the same icon. Because the current "freedom" is very confusing. Nobody knows what to do with so many allowed icon sizes.

Please forbid so many versions of icons, while it is not so late. It can save wepage authors 5 minutes of their lives. With 50 millions of web creators, it sums up to 482 years, which is about 7 human lives.

**Comment by mgiuca** [comment]
@photopea Yes, but as explained, a) there is still benefit to the developer pre-scaling the icons ahead of time so the user only has to download the size they need (to save bandwidth), and b) if you ignore this feature and just supply the highest resolution possible, everything will still work.

There is literally nothing to fix here; all you are asking for is that an optional feature be removed, because you can't be bothered using it. Someone like Google or Facebook is absolutely going to want to spend the extra minutes/hours of design and engineering time to make their icons look good at every scale with minimal bandwidth. You don't have to.

**Comment by photopea** [comment]
>  if you ignore this feature and just supply the highest resolution possible, everything will still work

This is not obvious to most of the people. When they say, that it is possible to include several icon sizes, they will do their "research" and start resizing the same icon into many sizes.

People already do research here: https://stackoverflow.com/questions/48839338/which-icon-sizes-are-required-for-progressive-web-apps-pwa-as-of-q1-2018

And there are many "services" for icon resizing: http://appiconmaker.co/, https://makeappicon.com/ . Millions of people will spend millions of hours doing something, what should be done automatically. You are going to waste peoples time by not making the specification more restricted. Don't you see it?

**Comment by tomayac** [comment]
Note that people still might want to optimize their icons for different sizes by showing different level of complexity or detail. It doesn't have to be purely a resized version of the same design.

**Comment by mgiuca** [comment]
@photopea As I've said above, it *is* done automatically (icon resizing). If you supply a high enough resolution icon, the browser will just size it correctly.

I don't see how allowing developers to supply multiple icons if they want is making life harder for developers who just want to supply one.
