### ISSUE TITLE
Manifest: one of 'url' or 'id' is required, related application ignored.

### ISSUE THREAD

**Issue by mbj36** [w3c/manifest#591]
I am receiving this error on my web app which is running at https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org

`Manifest: one of 'url' or 'id' is required, related application ignored`

What could be the workaround ?

**Comment by patrickkettner** [comment]
you are using `related_applications`, without specifying any related applications. That field is to link against related native applications. Since you don't appear to have any, you can just remove that from your manifest.

**Comment by mbj36** [comment]
Hey @patrickkettner I am using lighthouse to test my PWA which is at https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org#/

One of the audits fails in lighthouse which says `Failures: Manifest start_url is not cached by a Service Worker.` but i have cached my start_url. what could be the possible solution for this ?

![selection_053](https://user-images.githubusercontent.com/9936881/28743712-9b3a6ff8-746e-11e7-8ac1-8aee47f546f5.png)

**Comment by patrickkettner** [comment]
@mbj36
I would really suggest posting these sort of questions on stackoverflow, or the lighthouse github rather than on a standards issue list. This place is intended for issues within the manifest specification, rather than issues with your implementation of it.

That being said, load [your pwa](https://mbj36.github.io/community-app/#/), then open the `Application` tab in chrome's dev tools, and look at the `Cache Storage` section - your start_url (which does include the query string) is not being cached. You are caching `https://mbj36.github.io/community-app/index.html?_sw-precache=2297276cb767f82ac25b5730cab56b10`. While that resolves to the same page, that is not the same URL as far as the browser is concerned.
