### ISSUE TITLE
Fix shortname in w3c.json?

### ISSUE THREAD

**Issue by tripu** [w3c/manifest#605]
https://github.com/w3c/manifest/blob/9642178d97517c6c44dc7f6ec88c34990487ef53/w3c.json#L4

Shouldn't this be `appmanifest`?

**Comment by anssiko** [comment]
For what is the `shortName` in `w3c.json` used for by Echidna?

I'm wondering, since it seems https://www.w3.org/TR/appmanifest/ passes https://www.w3.org/pubrules/ without issues. Can we simply remove `shortName` entirely without breaking things?

(Note: this issue should not be confused with `short_name` defined in the Web App Manifest spec.)

**Comment by tripu** [comment]
@anssiko: you are right; Echidna does not need that information. Sorry about the confusion.

According to [the documentation](https://w3c.github.io/w3c.json.html), `shortName` should be the *spec* shortname, ie the one in `w3.org/TR/<shortname>`. But it seems that [Ash-Nazg (aka repo-manager)](https://github.com/w3c/ash-nazg/) actually expects to find there the *GH project name* (so, `manifest`, in your case`).

**Comment by anssiko** [comment]
OK, so we keep `shortName` to ensure repo-manager integration works.
