### ISSUE TITLE
Multiple authors / developers

### ISSUE THREAD

**Issue by benrogmans** [w3c/manifest#630]
Would be really nice if manifest.json had a property to list the people involved in creating the application.
For example:

`”credits”: []`

**Comment by RobDolin** [comment]
Interesting suggestion @benrogmans.  Can you explain more about how you envision this might be used?  Would this be like the "credits" that run at the end of a movie?

**Comment by benrogmans** [comment]
@RobDolin Yes, quite like that! As organisations are becoming more and more diffuse, It will be a nice property for people to proof that they belong to a project.

I guess it would be an array with objects á la `developer` (with properties `name` and `url`). A property `role` might also be nice.

**Comment by marcoscaceres** [comment]
For anything that resembles credits, it's best handled within the application itself. 

The utility of something like this would need to show some value via the user agent, OS, search engine, or app store (i.e., what demonstrable value is there to users?). 

In the last decade, we've made various attempts to add "author" type info to various manifest formats, but have found it to be of limited utility. 

For developer facing attribution, package.json files are probably better suited to record this information.

**Comment by benrogmans** [comment]
Package.json is a good option also. The use case why I actually got this
idea for credits is indeed to show this information in an app store (the
Blockstack Browser).

In contrary to package.json it is safe to assume that manifest.json is
publicly accessible. Also the key idea is that it is not just for developer
attribution but also to give designers, copy writers and others their
deserved credits in a computer readable standard format.

2017-12-04 13:06 GMT+08:00 Marcos Cáceres <notifications@github.com>:

**Comment by marcoscaceres** [comment]
> Package.json is a good option also. The use case why I actually got this
idea for credits is indeed to show this information in an app store (the
Blockstack Browser).

Ok, but it also doesn't show author info either... I guess they can't because they also use web manifest (🐓/🥚)  

> In contrary to package.json it is safe to assume that manifest.json is
publicly accessible. Also the key idea is that it is not just for developer
attribution but also to give designers, copy writers and others their
deserved credits in a computer readable standard format.

That still provides very little value to users (e.g., "this was made by random developer X and random designer Y, and copy writer W"... user: meh, 🤷🏽‍♂️). The bar needs to be much higher, like: "show me all apps made by X". Steam provides the ability to search by publisher and developer, which is useful, for instance, to find games by reputable publishers or developers:  

![screenshot_2017-12-04_16_24_01](https://user-images.githubusercontent.com/870154/33537460-ae1a946c-d90f-11e7-81b7-d6dc77b824c5.png)

The problem is still authenticity and trust... which search engines try solve... anyway, it's a hard problem. I'm still not super convinced that we would want to add anything at this point.

**Comment by benrogmans** [comment]
Ok well that's really too bad then
