### ISSUE TITLE
Question: Able to manually call beforeinstallprompt event?

### ISSUE THREAD

**Issue by pcanella** [w3c/manifest#674]
Hello all,

First of all, awesome job on this! I love the manifest functionality 👍 

My question is this:

Am I able to manually call `beforeinstallprompt` whenever I want? I wasn't sure if I was able to call `beforeinstallprompt` any time to trigger the "Add to Home Screen" banner to be shown to our users. I can get it to work the first time the user enters the site, but if they ignore it, it never comes up again (at least on Android simulator). Any advice/thoughts here? Please let me know. 

Thanks!

- Patrick

**Comment by mgiuca** [comment]
No, you aren't. It is designed so that the User Agent (browser) sends the event when it is prepared for you to show the prompt, and then you can show the prompt one time after receiving the event.

It is up to the User Agent to fire the event again if it thinks it's appropriate for you to show a prompt a second time. On Chrome on Desktop, we fire the event again after the user cancels the dialog. On Android, we currently don't.
