### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by jackpalmer1** [w3c/manifest#686]
Asking permissions one by one is annoying to the user. We have done A/B testing, users are less likely to award permissions if asked individually because they just consider it an annoyance.  The individual permission based system for websites is not suitable for installed or about to be installed webapps. We ask for all permissions related to the app that can be used in the app, in the beginning of install process of our app. It is smooth experience, and provides a much better expectation. In our android app, we ask for camera access, microphone access, location access, notification, reading sms etc in one go. 

When the user is installing an app, they should be able to award all permissions to the app in one go like a respectable native app. This is necessary, because we have significant amount of people declining permission and complaining that app does not work. For example when the user expects to order food in our app, we have to explain the user why the permission is needed. Instead of reading, they just close the app and restart it.

What we propose is that all required permissions are declared in the manifest and asked fo at the same time during install.

**Comment by marcoscaceres** [comment]
> When the user is installing an app, they should be able to award all permissions to the app in one go like a respectable native app. 

Just noting that wrt "respectable native app", Android does not do this anymore. And iOS never supported this model. The web also does not support this model.  

These models are supported at the OS level, so even if we wanted to do this (which we honestly don't, because the blanker permission model is not ideal) - we could not do this. 

Better is to follow [Apple's Permission request model](https://developer.apple.com/ios/human-interface-guidelines/app-architecture/requesting-permission/):

 * Request personal data only when your app clearly needs it.
 * Before asking, explain why your app needs the information if it’s not obvious.
 * Request permission at launch only when necessary for your app to function.
 * Don’t request location information unnecessarily.

**Comment by marcoscaceres** [comment]
@jackpalmer1 this article might be helpful for you (basically, best practice for iOS and Android): https://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

**Comment by dominickng** [comment]
As @marcoscaceres notes, neither iOS nor Android now asks or grants users for permissions in a block up front any more. The accepted best practice is to ask for permissions in context (as the web's permission model has always been designed to do) - ask only when you need to use the permission. Otherwise the user has to make a judgement call when they install your app whether they're willing to grant you the permissions you ask for (and often they don't have a clear view of why exactly you need all these permissions in the first place).

**Comment by jackpalmer1** [comment]
What I am asking is to stack up all the permissions. The user should of course be able to disable it, but they should an option to 'allow all requested'. For example, our app has to make a critical impression in the first few seconds, and our functionality requires location, microphone and camera access for the first task. It is very annoying as a user

**Comment by marcoscaceres** [comment]
@jackpalmer1, we are keenly familiar with what you are asking - browsers have even experimented with stacking before. However, stacking doesn't make a lot of sense, particularly when you "request personal data only when your app clearly needs it."
