### ISSUE TITLE
manifest.webmanifest or manifest.json

### ISSUE THREAD

**Issue by ghost** [w3c/manifest#689]
I notice the w3c spec mentions `manifest.webmanifest` yet I see Google and Firefox and other browsers say to use `manifest.json`

Simple question: Should we use both or just pick one? ~As I can't find the answer in the spec. Plus the spec doesn't mention `manifest.json` either which seems strange.

(I been using the `.json` and seen no problems for several years, just wondered if I should add both).

Thanks.

**Comment by marcoscaceres** [comment]
Using .json only is totally fine.

**Comment by marcoscaceres** [comment]
Leaving this open so we can add a note to the spec.

**Comment by ayumihamsaki** [comment]
Thank you.

**Comment by mgiuca** [comment]
Note that the actual name (including the extension) are totally irrelevant, as long as you serve it with application/json (perhaps it doesn't even matter if you serve it with application/json). However, `manifest.json` is far more likely to be served with a correct MIME type, so I would be in favour of converting all documentation over to recommend that.

**Comment by Malvoz** [comment]
[H5BP](https://github.com/h5bp/server-configs-apache/blob/9481d537d60d0226667a2f9712018a1ff4d799d8/dist/.htaccess#L190) does serve `.webmanifest` with `application/manifest+json`.

**Comment by nhoizey** [comment]
[I've been using `manifest.webmanifest` with a `application/manifest+json` MIME type for a while](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/.htaccess#L188), because:

- that's what I saw recommended (I don't remember where) when I created it
- it allows me to [use a different Expire header](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/.htaccess#L700) for manifests and other JSON files

**Comment by alrra** [comment]
> it allows me to use a different header for manifests and other JSON files

Yes, the main reason was to [make it easier to target the web app manifest file in the server configs](https://github.com/w3c/manifest/issues/346). But there were [other](https://github.com/w3c/manifest/issues/381).

**Comment by Malvoz** [comment]
@MatteoWebDesigner

The official media type for manifests is `application/manifest+json`, as long as you serve this media type you could have a manifest as a `.php` file for all that browsers care. If a developer doesn't have access to server configurations then `.json` would be the safest way to deploy the manifest.

However as an **example** consideration for serving manifests with the `application/manifest+json` (which is default for `.webmanifest` but not for `.json` files) is under "Security and privacy considerations" in the spec:

> ...because there is no way to prevent developers from including custom/unrestrained data in a manifest, implementors need to impose their own implementation-specific limits...

There are probably alot of implications for serving a manifest with `application/manifest+json` rather than `application/json` and might the reason why `.webmanifest` exists so that (eventually) developers wont have to care about the server config because the correct media type is defined and so is default for the file extension.

**Comment by marcoscaceres** [comment]
It also makes it easy to configure Apache and similar web servers, which is the main motivation.

**Comment by ayumihamsaki** [comment]
Going to close this as its old now and add a Summary:

The following methods are fine:

```html
<link rel="manifest" href="/manifest.json">
<link rel="manifest" href="/manifest.webmanifest">
```

Both must have the MIME type: `application/manifest+json`

**Comment by marcoscaceres** [comment]
To be clear, any file extension can be used - or no file extension at all. It’s polite to send the right mime type, but what matters is that the body of the response is JSON. However, if a file extension must be used, .webmanifest remains the standard one. 

We can add more guidance if you think it’s warranted.

**Comment by nhoizey** [comment]
@marcoscaceres I agree more guidance would be nice to prevent such future discussions

**Comment by Hoodlum-Z** [comment]
I've personally being using .webmanifest since I thought that is what is the correct choice, as discussed in the link below.

https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by uurcan7** [comment]
TR:
Merhaba konuyu tekrardan açmış oluyorum fakat
Tam olarak anlamadım
ben manifest.json Kullanıyorum manifest.webmanifest Geçmem gerekli mi ya da her ikisini de mi kullanmalıyım?
