### ISSUE TITLE
camelCase more suitable to JSON and JS API

### ISSUE THREAD

**Issue by AMorgaut** [w3c/manifest#72]
I feel acting as a devil advocate coming back to that topic, but as I think the newly introduced naming convention, which is finally not the one we ended too before, introduce a new issue.

It is related to these issues:
- #7 (Inconsistant naming of members)
- #50 (The manifest as a compliant JSON Package)

In the first issue we said we needed a naming convention. Discussion was about choosing between "_" which was used in google and firefox manifest files, and camelCase which is more standard in JS and JSON formats including "package.json" mentioned  in the second issue (but also [JSON Schema Validation](http://json-schema.org/latest/json-schema-validation.html), GData JSON representation, ...)

"_" looked to have been chosen for remote compatibility, but it looks like the "-" separator is known the one applied. So the remote compatibility argument is not valid anymore. I agree also that there is probably as much REST / JSON APIs out there using "_" than the ones using camelCase. It is often because the JSON format is a port of an XML version in which "_" is more standard or because the server language use this convention (ex: perl)

Current version of the specification use "-"...
"-" is used in CSS but is problematic in JSON once converted into JS object as it is not a valid character for JavaScript identifiers (while "_" was at least ok)

This is why CSS properties in JavaScript are turned into camelCase notation, and so do the vendor prefix notations:
- "background-color" vs "backgroundColor"
- "-webkit-app-region" (vendor CSS rule) vs webkitSpeechRecognition (Chrome API)

Potential impacts are that:
- such keys would require bracket notations if mapped as is in JS
- keys requiring bracket notation are usually not proposed for autocompletion
- user may expect a JS API to use a camelCase version or at least not expect having such named keys

Potentially concerned "properties" in the current edition of the specification are:
- "altname": no separator used, but I would have expected "altName" for consistency
- "dont-share-cookies-and-stuff": strangely long key, would need to be renamed "dontShareCookiesAndStuff", but may probably better have a shorter name
- vendor extensions as "webkit-fancyfeature" should better be "webkitFancyFeature"

**Comment by slang800** [comment]
It would be nice if we could revisit this with regards to `short_name`, `splash_screens`, `start_url`, `theme_color`, `related_applications`, `prefer_related_applications`, and `background_color`... It's a bit jarring to have to use underscores in JSON.

**Comment by marcoscaceres** [comment]
@slang800, given that this is now shipping in various browsers and related products, and given that there are now about ~50000 sites using manifests, it's too late to make these kinds of changes :(

**Comment by slang800** [comment]
It shouldn't be that hard to switch over while we're still in Working Draft status, right? Vendors just need to deprecate the old names, and support new camelCased ones... They can support both (giving websites time to switch over) until this at least becomes a Candidate Recommendation.

Plus, switching over should be really easy... you can probably do it with just sed:

```bash
sed -e 's/"short_name":/"shortName":/' \
    -e 's/"splash_screens":/"splashScreens":/' \
    -e 's/"start_url":/"startUrl":/' \
    -e 's/"theme_color":/"themeColor":/' \
    -e 's/"related_applications":/"relatedApplications":/' \
    -e 's/"prefer_related_applications":/"preferRelatedApplications":/' \
    -e 's/"background_color":/"backgroundColor":/' < manifest.webmanifest
```

**Comment by marcoscaceres** [comment]
@slang800 it's easy to change the spec, sure -  we would need to update all documentation, articles, various implementations, etc. And then we would basically be breaking all the content I mentioned previously for very little gain - even if we supported both camel case and "_". It's just not practical. We eff'ed up, and gotta live with it.

**Comment by slang800** [comment]
We haven't _really_ eff'ed up until this reaches CR status. As a Working Draft, breaking changes should be expected by both implementers and users. The draft stage is there for little mix-ups like this to be found by reviewers and get corrected so future users don't have to live with it... Which is why it doesn't demand backwards-compatibility between versions of the draft.

Also, I'm not suggesting that we support both naming forms in the spec - I'm saying that vendors could support both for a short period (perhaps with a deprecation notice), giving users time to switch over.

Lastly, I'd be happy to update all the documentation & articles for you. I'm not sure how much I can do for the various implementations, but for the ones that are open-source - I can probably help with those too.

**Comment by marcoscaceres** [comment]
> We haven't really eff'ed up until this reaches CR status...  

I don't think either Mozilla or Google would be willing to change their implementation (I'm not willing to change my Gecko implementation, at least). Technically, we are at CR in all but spec background-image (because we can't update the spec live if we move it to CR, so we are not interested in moving the spec to CR until the W3C addresses that flaw in the process) + we've started adding new features. However, core set of members has been stable for a long time. 

>  I'm saying that vendors could support both for a short period (perhaps with a deprecation notice), giving users time to switch over.

I don't think it's worth pain, tbh.  

> Lastly, I'd be happy to update all the documentation & articles for you. I'm not sure how much I can do for the various implementations, but for the ones that are open-source - I can probably help with those too.

That's very kind of you to offer, but no. This is really not something I'm willing to change at this point - even with help. It's not worth the pain. 

If you want to help, it would great if you could read over the spec and let me know if anything is not clear. We haven't had anyone give it a good read in a while and that would be really helpful.
