### ISSUE TITLE
Open PWA application from Android application

### ISSUE THREAD

**Issue by jayarajm** [w3c/manifest#820]
Is any possibility for open PWA application from native android application?

**Comment by aarongustafson** [comment]
Since you are speaking about Android specifically, [their Intent filters concept can do this in WebAPK](https://developers.google.com/web/fundamentals/integration/webapks#android_intent_filters).

Standards-wise, this is related to work we are doing on the [Service Worker Launch Event](https://wicg.github.io/sw-launch/explainer.html).
