### ISSUE TITLE
Update MDN Browser Compat Data

### ISSUE THREAD

**Issue by aarongustafson** [w3c/manifest#859]
It would be great if all of the browsers involved here could update the [Browser Compat Data @ MDN](https://github.com/mdn/browser-compat-data/) to reflect when specific manifest keys got implemented in desktop contexts.

**Comment by marcoscaceres** [comment]
@aarongustafson, last time I tried, it wasn't very clear how we update the data... it's a bit tricky because the files are a quite complicated to work with manually.

Having said that, the MDN info is currently linked and displayed in our spec... so I'm wondering if we just need to double check what is supported and what isn't across various UAs.

What might be nice would be for us to set aside a couple of hours (~2-3) to just run through each manifest member, and for us to confirm "yep, we do what the spec says" - even if we don't really have Web Platform Test to back it. It will be better than nothing, and we can update any incorrect information on MDN Data (or reach out for help to get things updated).

**Comment by aarongustafson** [comment]
I finally found out [where the bits are](https://github.com/mdn/browser-compat-data/tree/0137d48523c8ac12e67c26c655ee1e026ba45c2d/html/manifest), but yes I agree we should make a concerted effort to go through and clean it up as well as update our own, respective, bits.

**Comment by aarongustafson** [comment]
Adding @reezaali and @Maggers to this discussion as we were just talking about this in reference to their regular MDN sync.

**Comment by marcoscaceres** [comment]
I think we should transfer this issue over to the MDN-Data repo, as it's not a spec bug or anything we can do in the spec.

**Comment by marcoscaceres** [comment]
Created https://github.com/mdn/browser-compat-data/issues/6204
