### ISSUE TITLE
Shortcuts: Dynamic update or JS access to URLs

### ISSUE THREAD

**Issue by garykac** [w3c/manifest#867]
The [explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Shortcuts/explainer.md) mentions that allowing sites to "access or mutate Shortcuts via JavaScript" is "Non-goal for v1" and [this comment](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/35#issuecomment-480066697) (in the MS Edge Explainer repo) states "...when we can dynamically interact with them (which will be in v2)."

Is this v2 discussion already taking place somewhere?

**Comment by aarongustafson** [comment]
@rayankans is beginning work on the v2 Explainer. I will likely be involved in some capacity as well. You can see some of the prior concepts in @kenchris’ & @mgiuca’s explainers too:

* https://gist.github.com/kenchris/0acec2790cd38dfdff0a7197ff00d1de
* https://docs.google.com/document/d/1WzpCnpc1N7WjDJnFmj90-Z5SALI3cSPtNrYuH1EVufg/edit

If you’d like to get involved, please let me know. Otherwise we’ll kick off a discussion thread here (and likely WICG too) when we have something ready to share.

**Comment by bathos** [comment]
Is there any new info on this / somewhere where it’s being discussed openly now? The links seem to be from three years ago and don’t seem to be the right place for devs to share information about their use cases, etc.

**Comment by aarongustafson** [comment]
Yes: https://github.com/rayankans/app-shortcuts
