### ISSUE TITLE
Should dir and lang apply to name/description of app shortcuts?

### ISSUE THREAD

**Issue by xfq** [w3c/manifest#872]
The [dir](https://www.w3.org/TR/appmanifest/#dir-member) and [lang](https://www.w3.org/TR/appmanifest/#lang-member) members specify the base direction and language for the [directionality-capable members](https://www.w3.org/TR/appmanifest/#dfn-directionality-capable-members) of the manifest. The [directionality-capable members](https://www.w3.org/TR/appmanifest/#dfn-directionality-capable-members) are:

* [description](https://www.w3.org/TR/appmanifest/#description-member) member
* [name](https://www.w3.org/TR/appmanifest/#name-member) member
* [short_name](https://www.w3.org/TR/appmanifest/#short_name-member) member

I wonder if they apply to `name`, `short_name`, and `description` of [ShortcutItem](https://www.w3.org/TR/appmanifest/#shortcutitem-and-its-members) as well, since they're different from the members of the manifest itself (`WebAppManifest` dictionary).

**Comment by mgiuca** [comment]
As specified, no they don't apply, but perhaps they should.

I wonder if `dir` and `lang` have been implemented anywhere at all? [Chromium does not parse them](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/manifest/manifest_parser.cc). @marcoscaceres does Firefox use them?

I have never liked them, because it's weird to be forced to set the same directionality and language on all of the strings, rather than on a per-string basis.

I'm not sure what `lang` is even for. It says "knowing the language can also help with directionality" but there's nothing normative about how it is to be used (for example, it doesn't say that "base direction" is `dir` but falls back to the direction implied by `lang`, if `dir` is omitted... `lang` simply has no normative meaning in this spec).

It's theoretically useful to have `dir` so that the user agent can override the default paragraph direction when displaying these strings, but as I said, I don't think Chromium does this. It's also very rarely going to make a difference, since in most cases, if the string is in an RTL context, the outermost characters will be RTL, which means it will display properly anyway.

**Comment by xfq** [comment]
> I have never liked them, because it's weird to be forced to set the same directionality and language on all of the strings, rather than on a per-string basis.

Yes, I think that would be useful. As an example, the [Publication Manifest](https://w3c.github.io/pub-manifest/#manifest-lang-dir) provides the ability to set both these concepts globally as well as on individual items.

> I'm not sure what `lang` is even for. It says "knowing the language can also help with directionality" but there's nothing normative about how it is to be used (for example, it doesn't say that "base direction" is `dir` but falls back to the direction implied by `lang`, if `dir` is omitted... `lang` simply has no normative meaning in this spec).

For example, it can be used for selection of appropriate fonts (since the same code point can be rendered differently in different languages) or pronunciations (like screen readers). If we don't have consensus on how `lang` should be implemented now, we can mark the behavior as UA-dependent and add more normative text when the UA behaviors converge in the future.

**Comment by mgiuca** [comment]
> Yes, I think that would be useful. As an example, the [Publication Manifest](https://w3c.github.io/pub-manifest/#manifest-lang-dir) provides the ability to set both these concepts globally as well as on individual items.

Good precedent. I suppose we should not let the perfect (per-string settings) be the enemy of the good (global settings).

> For example, it can be used for selection of appropriate fonts (since the same code point can be rendered differently in different languages) or pronunciations (like screen readers). If we don't have consensus on how `lang` should be implemented now, we can mark the behavior as UA-dependent and add more normative text when the UA behaviors converge in the future.

I see. (I assume the "appropriate fonts" thing refers to [Han unification](https://en.wikipedia.org/wiki/Han_unification) for CJK languages.) I think we need a bit more normative text around `lang` for it to be useful. At the moment, it is too closely related to text directionality. For example, `lang` is specified as applying to "directionality-capable members". Perhaps we need to rename "directionality-capable members" to "user-facing string members", to reflect their role more accurately: these concerns (text direction, font choice, screen readers) are applicable to all strings that are intended to be displayed to the end user, as opposed to strings like URLs, IDs, enums, and colors.

**Comment by marcoscaceres** [comment]
> I wonder if dir and lang have been implemented anywhere at all? Chromium does not parse them. @marcoscaceres does Firefox use them?

Implemented, but not currently used anywhere I think.

> I'm not sure what lang is even for. 

Lang can sometimes be useful for pronunciation, but it would be messed up if the `name` was in one language and the `description` was in another.  

I tend to agree that global dir/lang might be doing more harm than good... we should perhaps drop them if they are not used anywhere.

**Comment by mgiuca** [comment]
> I tend to agree that global dir/lang might be doing more harm than good... we should perhaps drop them if they are not used anywhere.

See my above reply ("I suppose we should not let the perfect (per-string settings) be the enemy of the good (global settings).") I'm more convinced of the value now, since learning that `lang` has uses outside of directionality.

It's almost always going to be the same language used throughout, since you'll have your manifest be written for a specific language, and all fields will be localized to the same one. The exception to this is that the "name" might be different to the other fields, since you commonly have an English title that doesn't get localized, while all the other bits get translated. Still, it's unlikely to matter, since you could set your whole manifest to, say, Japanese, and still have an English title that will probably display correctly (since Han unification doesn't apply to English), and _may_ be screen-read in English but with a Japanese accent, which may even be desirable.

**Comment by marcoscaceres** [comment]
Ok, let's add `description` to the "directionality-capable members".

**Comment by mgiuca** [comment]
> Ok, let's add `description` to the "directionality-capable members".

It already is. The question here is whether the fields of `ShortcutItem` should become directionality-capable.

(Also, as a side proposal, I propose that we rename "directionality-capable" to "user-facing".)

**Comment by xfq** [comment]
> (Also, as a side proposal, I propose that we rename "directionality-capable" to "user-facing".)

"User-facing" might cause confusion, since members like `icons` and `screenshots` may also be considered "user-facing". So how about something like "natural language member" or "localizable strings"?

**Comment by mgiuca** [comment]
> "User-facing" might cause confusion, since members like `icons` and `screenshots` may also be considered "user-facing".

Sorry, I had originally suggested "user-facing string member" which is unambiguous, since for icons and screenshots, it is not the string that is user-facing. "Localizable" is also fine.

**Comment by aarongustafson** [comment]
I’m for "localizable string members." I am going to add here that we should include `ManifestImageResource.label` to this once #895 lands.
