### ISSUE TITLE
Remove store metadata into own spec or note?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#876]
The following members are app-store specific, and not likely to be meaningful within the context of a user agent:

 * categories
 * iarc_rating_id 
 * screenshots

Should we move them out to another spec or a Working Group Note?

**Comment by mgiuca** [comment]
I personally think that we place too much emphasis on the idea that a "user agent" has to be a web browser. We go to a lot of mental gymnastics to avoid using the term "web browser" in specs, instead using the generic term "user agent", and that's because the specs are intended to be interpreted by non-web-browser user agents as well.

The W3C [definition of a "user agent"](https://www.w3.org/WAI/UA/work/wiki/Definition_of_User_Agent) [this may be obsolete, since the actual spec it links to doesn't make this distinction] includes "Primary User Agents" (basically, web browsers) and "Web-Based User Agents" (basically, websites that interpret web content on behalf of the user).

An app store web page that reads a manifest file and displays it to the user _is a user agent_. Therefore, these fields are meaningful within the context of user agents — just not typically web browsers.

Whether there actually are any such web-based user agents that interpret these at the present time is another question, which we should answer in deciding whether to keep these things. If they are being used by at least two implementations, I think they should be kept in the spec as-is.

Preferably, this stuff would go into a sub-member of the manifest, but if they're already being used then it's too late for that.

**Comment by marcoscaceres** [comment]
I don't mind being more pragmatic... do we have two "things" (search engine? apps store?) that use these? I.e., could we make a credible argument that these are being used by more than one vendor at scale? 

More pragmatically tho, all the specs in the working group pertain/apply clearly to web browsers. We've generally avoided specifying things that work outside the context of web browser or that don't apply to a web page.

**Comment by kenchris** [comment]
PWA builder uses them at least for their pwa-install widget.

**Comment by kenchris** [comment]
Ping @jgw96

**Comment by NotWoods** [comment]
https://appsco.pe/ also uses screenshots and description

**Comment by marcoscaceres** [comment]
Talked about this with @aarongustafson. He'd be ok with us moving all these into a Note, where we can quickly add new stuff that is useful store stuff.

**Comment by aarongustafson** [comment]
https://progressiveapp.store/ seems to use `screenshots` and `description` as well.

**Comment by jgw96** [comment]
Hey all! Just wanted to jump in and confirm that yeah, our pwa-install component uses screenshots, description and others. We also have other interests in these store oriented metadata being in the manifest, including things like categories and the iarc_rating_id.

**Comment by marcoscaceres** [comment]
@jgw96, sorry, just to confirm, "pwa-install component" meaning in Edge, as part of the installation process?

**Comment by jgw96** [comment]
My bad, I should have been more clear. I was referring to this component by the PWABuilder team at Microsoft https://github.com/pwa-builder/pwa-install as @kenchris mentioned above.

**Comment by marcoscaceres** [comment]
ok, cool. Thanks for the clarification @jgw96!

**Comment by aarongustafson** [comment]
It’s in the PR thread, but I will note it here too: This content is moving to its own spec. https://github.com/w3c/manifest-app-info
