### ISSUE TITLE
Related applications members (at risk?)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#877]
The following members:
 
 * `related_applications`
 * `prefer_related_applications` 

Are single engine right now, so we need to poke other implementers about their level of interest and if they could be useful.  

They are perhaps also related to? 
https://wicg.github.io/get-installed-related-apps/spec/index.html

**Comment by mgiuca** [comment]
They are related to getInstalledRelatedApps (@rayankans) but not exclusive to that API. `related_applications` is also used by user agents (well, apparently just Chromium) to suggest installation of relevant native applications.

**Comment by aarongustafson** [comment]
Mentioned this in #862, but I think this could be moved to [App Info](https://github.com/w3c/manifest-app-info/).

**Comment by marcoscaceres** [comment]
We probably need to figure out what we are trying to achieve with getInstalledRelatedApps() first before we decide where it lives. Mozilla folks proposed some alternative design to `getInstalledRelatedApps` that's potentially more privacy preserving. However, if we can get rid of getInstalledRelatedApps() entirely (by addressing the push notification overlap issue), that would be better.

**Comment by mgiuca** [comment]
IIRC, the use case for `getInstalledRelatedApps` is no longer about push notification duplication (some history: I worked on GIRA back in 2017 when it first went through a Chrome origin trial, and at that time, we decided not to proceed with the API based on the grounds that the only use case, and it could be better solved by simply having user agents disable notifications for web apps by default if the related app was installed).

However, since then, the API has been revived by @rayankans, I believe based on emerging use cases such as those listed [here](https://web.dev/get-installed-related-apps/). IIRC the key use cases are for apps with a PWA and native version where the native version has a superset of the functionality. If the PWA knows that the native app is installed, it can just switch into that app, but if not, it can ask the user to install it.

**Comment by marcoscaceres** [comment]
> If the PWA knows that the native app is installed, it can just switch into that app, but if not, it can ask the user to install it.

This sounds a lot like "Smart App Banners" from Apple: 
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

Not saying we should use that, as it's very iOS specific - but just sounds quite similar. 

Just so it's a bit more clear, is the use case then for GIRA to only work on an installed web application? That is, does a user first need to install the PWA, then when they open the PWA they are told to use/install the native app instead?

**Comment by rayankans** [comment]
gIRA can be used to figure out if an app (PWA or native) is installed on the device.

The use case you mentioned is a potential one, but there are others, such as behavioural synchronization if both the native app/pwa is installed, metric collection, etc.

**Comment by aarongustafson** [comment]
I have a new scenario for `related_applications` in a forthcoming explainer. More soon.

**Comment by marcoscaceres** [comment]
Going to file individual issues for each of these that I can link to from the spec.

**Comment by marcoscaceres** [comment]
Filed #957 and #956.
