### ISSUE TITLE
Could you review Chrome/Firefox implementation regarding `fullscreen` display mode on Mac?

### ISSUE THREAD

**Issue by simevidas** [w3c/manifest#934]
The `fullscreen` display mode is defined as follows:

> Opens the web application without any user agent chrome and takes up the entirety of the available display area. 

https://w3c.github.io/manifest/#dom-displaymodetype-fullscreen

Desktop browsers can enter full screen. On Windows, a browser in full screen does not show any UI, i.e., the web content takes up the entire screen. However on Mac, even when a browser “enters full screen,” the browser’s UI is still fully shown.

![ndfiXy-gmEt-syJC](https://user-images.githubusercontent.com/716405/92946328-cbb19880-f456-11ea-9881-c7b68babf8a6.gif)

Considering the above “without any user agent chrome” definition, it seems to me that Mac browsers in full screen should not match the `fullscreen` display mode.

Chrome and Firefox do. Safari doesn’t. Which one is correct?

**Comment by marcoscaceres** [comment]
I think the spec is wrong... it's really whatever the OS convention is. 

About Safari. It probably doesn't support the media feature outside of iOS.

**Comment by mgiuca** [comment]
The spec, being a spec, can't really make definitive claims about the browser's UI. This makes it very hard to make concrete specifications about any display mode.

I think the spirit of it, however, is that "fullscreen" means there is no window dressing. This particular mode on Mac seems to just be essentially the same thing as "maximized" on Windows. Even if it's called "fullscreen", it should not correspond to the `"fullscreen"` display mode. I think Chrome and Firefox should change their behaviour here, not the spec.

I would, however, like to reword the spec to avoid the word "chrome". That is a very informal term that isn't defined anywhere, and also happens to be the name of a user agent, so it's quite a confusing sentence. In my experience, the term "chrome" to refer to the window dressing was popular in the 2000s, but has been less and less popular since Google Chrome has been around, due to the confusion.

@dmurph maybe something you could look into, as a low priority.
