### ISSUE TITLE
How could I participate and create an alwaysOnTop flag?

### ISSUE THREAD

**Issue by MickeyPickles** [w3c/manifest#938]
I'm building a PWA that could benefit from having an alwaysOnTop flag.  I believe it should work similarly as camera/mic/notifications.  The PWA should have the browser ask for alwaysOnTop permission and once its granted to the user it should be allowed to use it.  I've never done anything like this, where do I start?  Thanks!

**Comment by marcoscaceres** [comment]
Hmm... this strikes me as more of thing the OS should offer... but it also wouldn't make much sense across different OSs. The alternative might be to just use "fullscreen", which is more or less "always on top".

**Comment by christianliebel** [comment]
@MickeyPickles Looks like this feature was identified by the Second Screen CG for the Window Placement API: https://github.com/webscreens/window-placement/issues/10

I think it makes more sense to have it in this window-specific API instead of adding a general, application-wide flag to the manifest.

**Comment by marcoscaceres** [comment]
I'm going ahead and closing this as: 

 * it's an OS level thing
 * it may be covered by  https://github.com/w3c/window-placement/issues/10
