### ISSUE TITLE
Why does this spec replicate HTML features?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#97]
[Elsewhere](https://gist.github.com/marcoscaceres/7783977#comment-963173), @pornel wrote: 

We already have `<meta>`/`<link>` for most of the manifest:

``` JS
    {
      "name": "My App",
      "url": "/start.html",
      "mode": "standalone",
      "icons": [{
          "src": "icon/lowres",
          "width": "64",
          "type": "image/webp"
        }, {
          "src": "icon/hd",
          "width": "128"
      }]
    }
```

Can be written today, without reinventing the wheel, in a backwards-compatible way:

``` HTML
    <meta name="application-name" name="My App">
    <link rel=start href="/start.html">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel=icon sizes="64x64" type="image/webp" href="icon/lowres">
    <link rel=icon sizes="128x128" href="icon/hd">
```

And unlike JSON, it supports comments, internationalization and doesn't invalidate entire file because of a single trailing comma :)

``` HTML
    <meta name="application-name" name="My App" lang="en">
    <meta name="application-name" name="Moja Apka" lang="pl">
    <!-- I can comment things without breaking syntax, wow such amaze -->
    <link rel=icon href="es.png" hreflang=es>
    <!-- text in the icon? No problemo! -->
```

**Comment by OmidHekayati** [comment]
@marcoscaceres I think this issue must open again for these reasons:
- If devs want to have SSR web app (server-side rendering) they must accept that nobody wants to add an app to the home screen that shows browser errors in no internet situation. Manifest is part of PWA and one key purpose is not just app work offline by old caches but works offline natively (CSR client-side rendering). To achieve this, devs must handle lots of logic like routing, ... and best way to implement these needs always start apps with specific `main.html` file in any URL and browser can cache it once for start app in any URL by that file.
- As you mention above for security reason (app introduce itself to look like another app) and browser force serve PWA apps over TLS protocol and a certificate for TLS protocol belong to a domain, not URL, a domain can't set more than one app shortcut, so we just need one main HTML file.  So for the future, we must just read the app name and icon from certificate, not from the `manifest` or `main.html` file.

And also I think register another app logic process as `service-worker` also is a huge mistake in web standard due to just register one `main.js` to start an app is enough and devs can write the logic in desired order to handle everything.

I propose this way to tell the browser that our app can be PWA (or just has CSR ability)
```html
    <meta name="display" content="standalone">
    <meta name="theme-color" content="#66ff55">
    <link rel="start" href="/?utm_source=PWA&utm_medium=shortcut">
    <link rel="main" href="/gui/main.html">
    <script type="module" src="/gui/main.js" async></script>
```
By above CSR standard propsal that indicate a `main.html` file to render all URL, we also able to write a compiler to compile web apps to native OS apps easily.
(p.s. We consider to continue this approach, not use any manifest file and make a compiler like Flutter but in HTML standards, not complete new languages.)

Last but not least as lots of good face HTML specification never get standard like [@apply](http://tabatkins.github.io/specs/css-apply-rule/) in CSS, Editors must be brave to abandoned `manifest.webmanifest` file from specification before it's too late and uses some meta and link tags.
