### ISSUE TITLE
Remove sizes from icons?

### ISSUE THREAD

**Issue by dmurph** [w3c/manifest#997]
My core question here is - if a user agent can determine image sizes by fetching the image, why include the sizes in the manifest?

The only reason that I see this possibly being useful is detecting a 'diff' between two manifests - but since the image resource can also change, they all need to be fetched anyways.

Is there something I'm missing here? Why do we need to put image sizes in the manifest?

**Comment by NotWoods** [comment]
By including metadata like `sizes` and `type` in the manifest, the browser can determine the best icon without the need to download every image file, saving data for the user. Firefox (and Chromium, I think) read this metadata and only fetch the needed icon. Favicons using `<link>` tags work in a similar fashion.

**Comment by dmurph** [comment]
In Chromium we actually never use it - we download all icons and just use the sizes from the icon files. Then we resize to generate the sizes we want to have on hand (there is a static list of sizes we resize to) if there are any missing, and save on disk.

Same for updating - in order to support detecting changes to the application during update, we actually download all icons to detect if the contents are different.  So - we already have the size from that, no need to use the size in the manifest.

I guess a user agent, if it assumes it is always online, COULD just store the urls, and href all images to the corresponding urls if an icon has to be shown anywhere. I can totally see for things like `srcset` on images why the user agent would want this metadata so it could choose exactly which image to download (and then cache). But given the nature of webapps being saved to the os & that state is available offline - these sizes don't seem to be used.

I guess I see this as an opportunity to simplify the spec if we wanted.

**Comment by kenchris** [comment]
For SVG images, the user can decide which sizes that should apply to and use pixel optimized bitmap images for the remaining (especially smaller) sizes.

**Comment by aarongustafson** [comment]
I'd suggest we move this to ImageResource.

**Comment by EiraGe** [comment]
Chrome on Android actually are using the size field. We only fetch the needed(best fit) icon

**Comment by dominickng** [comment]
As @EiraGe mentioned, Chrome on Android downloads precisely one icon - the best fit icon - and uses the `sizes` member to determine which one that should be in order to minimize network usage.

As @NotWoods says, having `sizes` also allows the browser to fast fail if there is no icon available that meets installation requirements, rather than having to download all of them and check.

And as @kenchris says, `sizes` is particularly helpful for specifying when SVG icons should be used and when more pixel-optimised icons should be used (which is difficult to infer directly from the intrinsic size data of the icon).

**Comment by dmurph** [comment]
Thanks for the context everyone, this was helpful :)
