### ISSUE TITLE
Status report and planning for TPAC 2021

### ISSUE THREAD

**Issue by LJWatson** [w3c/manifest#999]
[TPAC](https://www.w3.org/2021/10/TPAC/#schedule) will be virtual again this year. There will be a WebApps WG meeting at some point between 24 and 29 October.

There are two things we need you to do in the meantime:
1. Let @marcoscaceres  and I know before 17 September if you plan to hold a specification specific meeting (in addition to the general WebApps WG meeting)
2. Post a specification status report before 30 September

Your specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

CC @siusin

**Comment by dotproto** [comment]
Hey WebApp Manifest folks. @xeenon and I are co-chairs of the [WebExtensions Community Group](https://www.w3.org/community/webextensions/). We're a relatively new CG focused on seeking alignment between  various stakeholders in the browser extension space in order to pave the way toward standardization.

The first major project we're tackling is a (rough) specification of the manifest.json file used by various browsers. As such, we are very interested in meeting with you to learn more about how you work, your experiences in this space, and any recommendations you have to help guide us in our work.

If you are open to it, the [TPAC guidebook page](https://www.w3.org/Guide/meetings/tpac.html) seems to indicate that we should either be targeting a joint session or a dedicated breakout session. 

If we were to do a joint session, I think we should focus on

* The process used to create the initial drafts of the WebApps Manifest specification.
* How changes are introduced to the WebApps Manifest spec.
* Technical issues related to manifest specification.
* Lessons learned and recommendations to help guide our manifest specification efforts.

If we were to do a breakout session, I think it may be useful to focus on the current state of specifying well structured JSON files for use in web browsers. Based on reading a few specific issues in this repository, it seems like the current tools available for specifying how browsers should parse and handle errors in large JSON objects are lacking. At the moment the only well defined JSON files I'm aware of are our respective manifests, but this seems like it may be a topic of general interest and use for the broader web community.

**Comment by dmurph** [comment]
Potential topics of current work if people would like to discuss them:
* Manifest Unique Identifier
* File Handlers
* Protocol Handlers
* Scope Extensions
* URL Handlers
* Multi Apps

Other things the community might want to talk about?
* App Catalog Install API?

A lot of discussion has been already happening over github issues though - so I don't think it's necessary to talk about these unless folks want to.

**Comment by marcoscaceres** [comment]
@dmurph, @dotproto, sorry for the delay. I'll set up a calendar entry now and slot in 2 hours. I'm thinking we will meet on Monday, 25 October 2021 at 21:00:00 UTC: 

Melbourne (Australia - Victoria) | Tuesday, 26 October 2021 at 8:00:00 am | AEDT | UTC+11 hours
-- | -- | -- | --
San Francisco (USA - California) | Monday, 25 October 2021 at 2:00:00 pm | PDT | UTC-7 hours
London (United Kingdom - England) | Monday, 25 October 2021 at 10:00:00 pm | BST | UTC+1 hour
Corresponding UTC (GMT) | Monday, 25 October 2021 at 21:00:00

**Comment by marcoscaceres** [comment]
I put together an agenda for next Monday: 

https://github.com/w3c/webappswg/wiki/TPAC-2021#agenda-for-web-manifest---monday-meeting

@dotproto, I allocated some time to go over the Extension CG's questions at the start of the meeting. 

Folks, please let me know if there are other high priority topics you'd like to cover.
